Repository reposense/RepoSense, pull requests merged in 2018-11, with the labels that each got.

#388 Show analysis period for total contribution in code panel #386
  frontend/src/index.jade
Labels: s.ToMerge

#384 Code panel: make the expand/collapse button a toggle button #376
  frontend/src/index.jade
  frontend/src/static/js/main.js
Labels: s.ToReview

#397 Fix unhandled IllegalArgumentException in RepoConfiguration#update #395
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/report/ReportGenerator.java
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
  src/test/java/reposense/parser/RepoConfigurationTest.java
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.ToReview

#400 Hotfix for recent outburst of RuntimeException
  src/main/java/reposense/report/ReportGenerator.java
Labels: s.ToReview

#387 Show breakdown of file type for total contribution in code panel #385
  frontend/src/index.jade
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_authorship.js
Labels: s.FinalReview
