Repository reposense/RepoSense, pull requests merged in 2018-07, with the labels that each got.

#150 Modification to accommodate netlify
  .gitignore
  .travis.yml
  src/functional/java/reposense/Entry.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/util/FileUtil.java
  src/test/java/reposense/parser/ArgsParserTest.java
Labels: s.FinalReview

#162 Update travis and remove legacy template
  .travis.yml
  frontend/.eslintrc.json
  frontend/package.json
  frontend/src/static/js/api.js
  frontend/src/static/js/main.js
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_summary.js
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/util/Constants.java
  src/main/java/reposense/util/FileUtil.java
  template/index.html
  template/repo_report/temp
  template/static/css/_colors.css
  template/static/css/style.css
  template/static/js/api.js
  template/static/js/main.js
  template/static/js/v_authorship.js
  template/static/js/v_summary.js
Labels: s.ToReview

#151 Update developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/developer_guide.md
  docs/diagrams/architecture.pptx
  docs/images/architecture.png
  docs/images/dashboard-architecture.png
  docs/images/dashboard-architeture.png
  docs/images/import-order.png
Labels: s.FinalReview

#176 Frontend: update the user guide
  docs/UserGuide.md
Labels: s.ToReview

#163 Dashboard revamp
  .travis.yml
  docs/UserGuide.md
  frontend/.eslintrc.json
  frontend/package.json
  frontend/src/index.jade
  frontend/src/static/css/_colors.scss
  frontend/src/static/css/style.scss
  frontend/src/static/js/api.js
  frontend/src/static/js/main.js
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_summary.js
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/util/Constants.java
  src/main/java/reposense/util/FileUtil.java
  template/index.html
  template/repo_report/index.html
  template/repo_report/result.js
  template/static/css/collapse.css
  template/static/css/highlight-tomorrow.css
  template/static/css/style.css
  template/static/img/right.png
  template/static/img/star.png
  template/static/js/api.js
  template/static/js/main.js
  template/static/js/v_authorship.js
  template/static/js/v_summary.js
  template/static/scripts/lib/highlight.pack.js
  template/static/scripts/lib/jquery.collapsible.min.js
  template/static/scripts/summaryVueMethods.js
  template/static/scripts/utils.js
  template/summary.js
Labels: s.ToMerge

#178 Add more default file types to analyze #177
  src/functional/java/reposense/Entry.java
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/main/java/reposense/commits/CommitInfoExtractor.java
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/system/CommandRunner.java
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
  src/test/java/reposense/system/CommandRunnerTest.java
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.ToMerge

#180 FileInfoExtractor: decode non-UTF-8 characters #182 #183
  src/main/java/reposense/authorship/FileInfoAnalyzer.java
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
  src/test/resources/FileInfoExtractorTest/fileWithSpecialCharacters.txt
  src/test/resources/FileInfoExtractorTest/fileWithoutSpecialCharacters.txt
Labels: s.ToReview

#187 Fix dashboard padding function
  frontend/src/static/js/api.js
  frontend/src/static/js/v_summary.js
  sample.csv
  template/static/js/api.js
  template/static/js/v_summary.js
Labels: s.ToReview

#159 Add support for user-supplied file formats #56, #177
  docs/UserGuide.md
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/main/java/reposense/commits/CommitInfoExtractor.java
  src/main/java/reposense/model/CliArguments.java
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/parser/AlphanumericArgumentType.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/system/CommandRunner.java
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/system/CommandRunnerTest.java
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.ToReview

#198 Fix ramp chart positioning #197
  frontend/src/index.jade
  frontend/src/static/js/v_summary.js
Labels: s.ToReview

#205 Authorship: incorrect line authorship when analyzing date range #203
  src/functional/resources/dateRange/expected/reposense_testrepo-Beta_master/authorship.json
  src/functional/resources/dateRange/expected/reposense_testrepo-Beta_master/commits.json
  src/functional/resources/dateRange/expected/reposense_testrepo-Charlie_master/authorship.json
  src/functional/resources/dateRange/expected/reposense_testrepo-Charlie_master/commits.json
  src/main/java/reposense/authorship/FileInfoAnalyzer.java
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/main/java/reposense/authorship/model/FileInfo.java
  src/main/java/reposense/authorship/model/LineInfo.java
  src/main/java/reposense/system/CommandRunner.java
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
  src/test/java/reposense/system/CommandRunnerTest.java
Labels: s.ToReview

#216 Extracting info from git diff is not working as expected #215
  src/main/java/reposense/authorship/FileInfoExtractor.java
Labels: s.ToReview

#211 Add functionality to start the web server to display the dashboard
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/model/CliArguments.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/system/DashboardServer.java
  src/test/java/reposense/parser/ArgsParserTest.java
Labels: s.ToMerge

#210 Allow location to be supplied into CSV Config File
  docs/UserGuide.md
  sample.csv
  src/functional/resources/dateRange/expected/summary.json
  src/functional/resources/noDateRange/expected/summary.json
  src/functional/resources/sample.csv
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/main/java/reposense/builder/ConfigurationBuilder.java
  src/main/java/reposense/commits/CommitInfoExtractor.java
  src/main/java/reposense/git/GitDownloader.java
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/parser/CsvParser.java
  src/main/java/reposense/parser/InvalidLocationException.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/system/CommandRunner.java
  src/main/java/reposense/util/Constants.java
  src/main/java/reposense/util/FileUtil.java
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
  src/test/java/reposense/git/GitCheckerTest.java
  src/test/java/reposense/system/CommandRunnerTest.java
  src/test/java/reposense/template/GitTestTemplate.java
  src/test/java/reposense/util/TestConstants.java
Labels: s.ToReview

#229 Add support for file exclusion patterns #218
  docs/UserGuide.md
  sample.csv
  src/functional/resources/sample.csv
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/main/java/reposense/builder/ConfigurationBuilder.java
  src/main/java/reposense/commits/CommitInfoExtractor.java
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/parser/CsvParser.java
  src/main/java/reposense/system/CommandRunner.java
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
  src/test/java/reposense/system/CommandRunnerTest.java
Labels: s.ToMerge

#157 CommitsReporter: add support for per-commit-view
  src/functional/resources/dateRange/expected/reposense_testrepo-Beta_master/commits.json
  src/functional/resources/dateRange/expected/reposense_testrepo-Charlie_master/commits.json
  src/functional/resources/noDateRange/expected/reposense_testrepo-Beta_master/commits.json
  src/functional/resources/noDateRange/expected/reposense_testrepo-Charlie_master/commits.json
  src/main/java/reposense/commits/CommitResultAggregator.java
  src/main/java/reposense/commits/model/AuthorDailyContribution.java
  src/main/java/reposense/commits/model/AuthorIntervalContribution.java
  src/main/java/reposense/commits/model/CommitContributionSummary.java
  src/main/java/reposense/commits/model/CommitResult.java
  src/main/java/reposense/report/CommitReportJson.java
  src/main/java/reposense/system/CommandRunner.java
Labels: s.ToMerge

#168 Fix code panel not showing the correct files #214
  frontend/src/index.jade
  frontend/src/static/js/main.js
  frontend/src/static/js/v_authorship.js
Labels: s.ToReview

#235 Include timestamp footer in the dashboard
  frontend/src/index.jade
  frontend/src/static/css/style.scss
  frontend/src/static/js/api.js
  frontend/src/static/js/main.js
  src/functional/java/reposense/Entry.java
  src/functional/resources/dateRange/expected/summary.json
  src/functional/resources/noDateRange/expected/summary.json
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/report/SummaryReportJson.java
Labels: s.ToReview

#232 Support repository standalone configuration #217
  _reposense/config.json
  docs/StandaloneConfiguration.md
  docs/UserGuide.md
  docs/example.csv
  src/functional/resources/dateRange/expected/reposense_testrepo-Delta_master/authorship.json
  src/functional/resources/dateRange/expected/reposense_testrepo-Delta_master/commits.json
  src/functional/resources/dateRange/expected/summary.json
  src/functional/resources/noDateRange/expected/reposense_testrepo-Delta_master/authorship.json
  src/functional/resources/noDateRange/expected/reposense_testrepo-Delta_master/commits.json
  src/functional/resources/noDateRange/expected/summary.json
  src/functional/resources/sample.csv
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/model/StandaloneAuthor.java
  src/main/java/reposense/model/StandaloneConfig.java
  src/main/java/reposense/parser/CsvParser.java
  src/main/java/reposense/parser/JsonParser.java
  src/main/java/reposense/parser/StandaloneConfigJsonParser.java
  src/main/java/reposense/report/ReportGenerator.java
  src/test/java/reposense/parser/RepoConfigurationTest.java
Labels: s.ToReview

#247 Update data for testrepo-Delta
  src/functional/resources/noDateRange/expected/reposense_testrepo-Delta_master/authorship.json
  src/functional/resources/noDateRange/expected/reposense_testrepo-Delta_master/commits.json
  src/test/java/reposense/parser/RepoConfigurationTest.java
Labels: s.ToReview

#227 Dashboard: determine date range only after all repo data are loaded
  frontend/src/static/css/style.scss
  frontend/src/static/js/api.js
  frontend/src/static/js/main.js
  frontend/src/static/js/v_authorship.js
Labels: s.Ongoing

#250 Add RepoSense to sample config
  sample.csv
Labels: s.ToReview

#160 Dashboard: restore view state using query parameters #224
  frontend/src/index.jade
  frontend/src/static/js/api.js
  frontend/src/static/js/main.js
  frontend/src/static/js/v_summary.js
Labels: s.ToReview

#252 Dashboard does not work with microsoft edge #239
  frontend/src/static/js/main.js
Labels: s.ToReview

#251 Some browsers show extra element #209
  frontend/src/static/css/style.scss
Labels: s.ToReview

#253 Dashboard unable to load authorship.json file #254
  frontend/src/static/js/v_authorship.js
Labels: s.ToReview
