Repository reposense/RepoSense, pull requests merged in 2018-12, with the labels that each got.

#410 Gradle task npmRunSpuild is not working as intended #409
  package.json
Labels: s.ToReview

#242 Developer docs for frontend
  docs/DeveloperGuide.md
  docs/diagrams/dashboard-architecture.pptx
  docs/diagrams/dashboard-screenshot.odg
  docs/images/dashboard-architecture-authorship.png
  docs/images/dashboard-architecture-summary.png
  docs/images/dashboard-architecture.png
  docs/images/dashboard.png
Labels: s.FinalReview

#416 DeveloperGuide: Update gradle command to gradle test systemtest
  docs/DeveloperGuide.md
Labels: s.ToReview

#420 Fix appearance of search text and hide auto-changes to lowercase from user.
  docs/UserGuide.md
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#432 Undefined parameter in the URL #393
  frontend/src/static/js/v_summary.js
Labels: s.FinalReview

#422 Sort order name: rename from Team to Repo/Branch #30
  docs/UserGuide.md
  frontend/src/index.jade
Labels: s.ToMerge

#415 [#199] Clean Docs of Confusing Dates
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: s.ToMerge

#412 Make StandaloneConfig foolproof to exceptions caused by trailing commas #402
  src/main/java/reposense/model/StandaloneAuthor.java
  src/main/java/reposense/model/StandaloneConfig.java
  src/test/java/reposense/model/StandaloneConfigTest.java
  src/test/resources/StandaloneConfigTest/authors_trailingCommas_config.json
  src/test/resources/StandaloneConfigTest/lithiumlkid_trailingCommas_config.json
Labels: s.ToMerge

#428 [#405] Code view: reset to top when loading new code view
  frontend/src/static/js/main.js
Labels: s.ToMerge

#408 Apply SRP to various git commands #310
  docs/DeveloperGuide.md
  docs/diagrams/architecture.pptx
  docs/images/architecture.png
  src/main/java/reposense/authorship/FileInfoAnalyzer.java
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/main/java/reposense/commits/CommitInfoExtractor.java
  src/main/java/reposense/git/GitBlame.java
  src/main/java/reposense/git/GitBranch.java
  src/main/java/reposense/git/GitChecker.java
  src/main/java/reposense/git/GitCheckout.java
  src/main/java/reposense/git/GitClone.java
  src/main/java/reposense/git/GitCloneException.java
  src/main/java/reposense/git/GitDiff.java
  src/main/java/reposense/git/GitDownloader.java
  src/main/java/reposense/git/GitDownloaderException.java
  src/main/java/reposense/git/GitLog.java
  src/main/java/reposense/git/GitRevList.java
  src/main/java/reposense/git/GitShortlog.java
  src/main/java/reposense/git/GitUtil.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/system/CommandRunner.java
  src/main/java/reposense/util/StringsUtil.java
  src/test/java/reposense/authorship/FileAnalyzerTest.java
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
  src/test/java/reposense/git/GitBlameTest.java
  src/test/java/reposense/git/GitBranchTest.java
  src/test/java/reposense/git/GitCheckoutTest.java
  src/test/java/reposense/git/GitCloneTest.java
  src/test/java/reposense/git/GitDiffTest.java
  src/test/java/reposense/git/GitLogTest.java
  src/test/java/reposense/git/GitRevListTest.java
  src/test/java/reposense/git/GitShortlogTest.java
  src/test/java/reposense/parser/RepoConfigurationTest.java
  src/test/java/reposense/system/CommandRunnerTest.java
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.ToReview

#434 Show breakdown of blank line for total contribution in code panel #427
  frontend/src/index.jade
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_authorship.js
Labels: s.FinalReview

#425 Split repo configuration #316
  frontend/src/static/js/api.js
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/authorship/FileInfoAnalyzer.java
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/main/java/reposense/builder/ConfigurationBuilder.java
  src/main/java/reposense/commits/CommitInfoAnalyzer.java
  src/main/java/reposense/git/GitClone.java
  src/main/java/reposense/git/GitUtil.java
  src/main/java/reposense/model/CliArguments.java
  src/main/java/reposense/model/CommitHash.java
  src/main/java/reposense/model/ConfigCliArguments.java
  src/main/java/reposense/model/Format.java
  src/main/java/reposense/model/LocationsCliArguments.java
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/model/RepoLocation.java
  src/main/java/reposense/model/StandaloneConfig.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/parser/AuthorConfigCsvParser.java
  src/main/java/reposense/parser/CsvParser.java
  src/main/java/reposense/parser/RepoConfigCsvParser.java
  src/systemtest/resources/dateRange/expected/summary.json
  src/systemtest/resources/noDateRange/expected/summary.json
  src/test/java/reposense/authorship/FileAnalyzerTest.java
  src/test/java/reposense/commits/CommitInfoAnalyzerTest.java
  src/test/java/reposense/git/GitBranchTest.java
  src/test/java/reposense/git/GitDiffTest.java
  src/test/java/reposense/git/GitLogTest.java
  src/test/java/reposense/model/CommitHashTest.java
  src/test/java/reposense/model/FormatTest.java
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/parser/CsvParserTest.java
  src/test/java/reposense/parser/RepoConfigurationTest.java
  src/test/java/reposense/parser/StandaloneConfigJsonParserTest.java
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.ToReview
