Repository reposense/RepoSense, pull requests merged in 2018-10, with the labels that each got.

#339 Dashboard crashes when modify date to be out of range #336
  frontend/src/index.jade
  frontend/src/static/js/v_summary.js
Labels: s.ToReview

#355 granularity#week: fix url not using correct time gap #354
  frontend/src/static/js/v_summary.js
Labels: s.ToReview

#364 Make the commits info analysis case insensitive #363
  src/main/java/reposense/system/CommandRunner.java
  src/test/java/reposense/system/CommandRunnerTest.java
Labels: s.ToReview

#368 Fix NullPointerException when accessing empty displayName in StandaloneConfig #366
  src/main/java/reposense/model/Author.java
  src/main/java/reposense/model/StandaloneAuthor.java
  src/test/java/reposense/parser/RepoConfigurationTest.java
  src/test/java/reposense/parser/StandaloneConfigJsonParserTest.java
  src/test/java/reposense/util/TestUtil.java
  src/test/resources/StandaloneConfigJsonParserTest/standaloneConfig_emptyJson.json
  src/test/resources/StandaloneConfigJsonParserTest/standaloneConfig_emptyText.json
  src/test/resources/StandaloneConfigJsonParserTest/standaloneConfig_full.json
  src/test/resources/StandaloneConfigJsonParserTest/standaloneConfig_githubId_only.json
  src/test/resources/StandaloneConfigJsonParserTest/standaloneConfig_malformedJson.json
  src/test/resources/StandaloneConfigJsonParserTest/standaloneConfig_unknownPropertyInJson.json
Labels: s.ToMerge

#359 Report#datepicker: default value not filled on initial load #358
  frontend/src/index.jade
  frontend/src/static/js/v_summary.js
Labels: s.ToReview

#371 InvalidPathException thrown during run time due to Illegal char <:> in file name #370
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
  src/test/java/reposense/util/TestUtil.java
Labels: s.ToMerge

#332 Make branch an optional field #323
  docs/UserGuide.md
  src/main/java/reposense/git/GitDownloader.java
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/parser/AuthorConfigCsvParser.java
  src/main/java/reposense/parser/CsvParser.java
  src/main/java/reposense/parser/RepoConfigCsvParser.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/system/CommandRunner.java
  src/systemtest/resources/author-config.csv
  src/systemtest/resources/repo-config.csv
  src/test/java/reposense/git/GitCheckerTest.java
  src/test/java/reposense/parser/CsvParserTest.java
  src/test/java/reposense/system/CommandRunnerTest.java
  src/test/resources/cli_location_test/repo-config.csv
  src/test/resources/repoconfig_empty_branch_test/author-config.csv
  src/test/resources/repoconfig_empty_branch_test/repo-config.csv
Labels: s.ToMerge

#372 Show total contribution in code panel #369
  frontend/src/index.jade
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_authorship.js
Labels: s.ToMerge

#365 Show analysis period in contribution bar tooltip #362
  frontend/src/index.jade
Labels: s.FinalReview
