Repository reposense/RepoSense, pull requests merged in 2018-05, with the labels that each got.

#62 DeveloperGuide: add setup instructions
  docs/developer_guide.md
Labels: s.ToReview

#64 Setup Travis CI
  .travis.yml
  README.md
  config.csv
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
  config/travis/check-eof-newline.sh
  config/travis/check-line-endings.sh
  config/travis/check-trailing-whitespace.sh
  config/travis/run-checks.sh
  docs/user_guide.md
  gradle.properties
  gradlew.bat
  sample_full.csv
  sample_small.csv
  src/functional/resources/sample_full.csv
  src/main/java/system/Console.java
  template/index.html
  template/repo_report/index.html
  template/static/css/collapse.css
  template/static/css/style.css
  template/static/scripts/lib/highlight.pack.js
  template/static/scripts/lib/jquery.collapsible.min.js
  template/static/scripts/summaryVueMethods.js
  template/static/scripts/utils.js
Labels: s.ToReview

#65 Travis: add checkstyle to CI test
  .travis.yml
  build.gradle
  config/checkstyle/checkstyle.xml
  src/functional/java/Entry.java
  src/main/java/analyzer/AnnotatorAnalyzer.java
  src/main/java/analyzer/CheckStyleParser.java
  src/main/java/analyzer/ContentAnalyzer.java
  src/main/java/analyzer/FileAnalyzeThread.java
  src/main/java/analyzer/FileAnalyzer.java
  src/main/java/analyzer/FileInfoGenerator.java
  src/main/java/analyzer/MethodAnalyzer.java
  src/main/java/analyzer/RepoAnalyzer.java
  src/main/java/builder/ConfigurationBuilder.java
  src/main/java/dataObject/Author.java
  src/main/java/dataObject/AuthorIntervalContribution.java
  src/main/java/dataObject/CommitInfo.java
  src/main/java/dataObject/FileInfo.java
  src/main/java/dataObject/LineInfo.java
  src/main/java/dataObject/MethodInfo.java
  src/main/java/dataObject/RepoConfiguration.java
  src/main/java/dataObject/RepoContributionSummary.java
  src/main/java/dataObject/RepoInfo.java
  src/main/java/frontend/Client.java
  src/main/java/frontend/Gui.java
  src/main/java/frontend/RepoSense.java
  src/main/java/git/GitBlamer.java
  src/main/java/git/GitChecker.java
  src/main/java/git/GitCloner.java
  src/main/java/git/GitClonerException.java
  src/main/java/git/GitLogger.java
  src/main/java/report/ContributionSummaryGenerator.java
  src/main/java/report/RepoInfoFileGenerator.java
  src/main/java/system/CommandRunner.java
  src/main/java/system/Console.java
  src/main/java/system/CsvConfigurationBuilder.java
  src/main/java/system/StreamGobbler.java
  src/main/java/util/FileUtil.java
  src/test/java/analyzer/AnnotatorAnalyzerTest.java
  src/test/java/analyzer/FileAnalyzerTest.java
  src/test/java/analyzer/RepoAnalyzerTest.java
  src/test/java/git/GitBlamerTest.java
  src/test/java/git/GitCheckerTest.java
  src/test/java/git/GitLoggerTest.java
  src/test/java/system/CommandRunnerTest.java
  src/test/java/template/GitTestTemplate.java
  src/test/java/util/TestConstants.java
Labels: s.ToReview

#67 README: embed travis status badge
  README.md
Labels: s.ToReview

#66 remove log message when trying to delete non-existing directory
  src/main/java/git/GitCloner.java
  src/main/java/util/FileUtil.java
Labels: s.ToReview

#74 Move test repos inside reposense org #73
  src/test/java/util/TestConstants.java
Labels: s.ToReview

#77 Remove GUI #70
  docs/user_guide.md
  src/main/java/frontend/Client.java
  src/main/java/frontend/Gui.java
  src/main/java/frontend/RepoSense.java
Labels: s.FinalReview

#68 Gradle: replace build with shadowJar plugin
  build.gradle
  docs/Build.md
  docs/user_guide.md
Labels: s.FinalReview

#76 Docs: add using Checkstyle-IDEA plugin on IntelliJ
  docs/UsingCheckstyle.md
  docs/developer_guide.md
  docs/images/checkstyle-idea-configuration.png
  docs/images/checkstyle-idea-scan-scope.png
Labels: s.ToReview

#83 Gradle: upgrade to version 4.7
  .travis.yml
  build.gradle
  docs/developer_guide.md
  docs/user_guide.md
  gradle/wrapper/gradle-wrapper.properties
Labels: s.ToReview

#104 Remove threading #72
  src/main/java/reposense/analyzer/FileAnalyzeThread.java
  src/main/java/reposense/analyzer/FileAnalyzer.java
Labels: s.ToReview

#95 Remove RepoInfo's dependency on FileInfo #69
  src/main/java/reposense/analyzer/ContentAnalyzer.java
  src/main/java/reposense/analyzer/RepoAnalyzer.java
  src/main/java/reposense/dataobject/RepoInfo.java
  src/main/java/reposense/report/RepoInfoFileGenerator.java
Labels: s.ToReview

#99 Apply single responsibility principle to frontend component
  src/main/java/reposense/exception/ParseException.java
  src/main/java/reposense/frontend/CliArguments.java
  src/main/java/reposense/frontend/Client.java
  src/main/java/reposense/frontend/RepoSense.java
  src/main/java/reposense/parser/DateParser.java
Labels: s.ToMerge

#122 TestUtil: add file content comparison method
  build.gradle
  src/functional/java/reposense/Entry.java
  src/test/java/reposense/util/TestUtil.java
Labels: s.FinalReview

#109 Ramp chart: optimize vertical space #21
  docs/images/dashboard.png
  docs/images/rampchart.jpg
  docs/images/rampchart.png
  docs/user_guide.md
  template/index.html
  template/static/css/style.css
Labels: s.ToMerge

#114 Shift from File to Path class #107
  src/functional/java/reposense/Entry.java
  src/main/java/reposense/analyzer/FileAnalyzer.java
  src/main/java/reposense/analyzer/FileInfoGenerator.java
  src/main/java/reposense/frontend/CliArguments.java
  src/main/java/reposense/frontend/RepoSense.java
  src/main/java/reposense/git/GitCloner.java
  src/main/java/reposense/report/RepoInfoFileGenerator.java
  src/main/java/reposense/system/CommandRunner.java
  src/main/java/reposense/system/CsvConfigurationBuilder.java
  src/main/java/reposense/util/FileUtil.java
  src/test/java/reposense/analyzer/FileAnalyzerTest.java
  src/test/java/reposense/git/GitCheckerTest.java
  src/test/java/reposense/system/CommandRunnerTest.java
  src/test/java/reposense/template/GitTestTemplate.java
  src/test/java/reposense/util/TestUtil.java
Labels: s.ToMerge

#125 Fix datetime inconsistency
  docs/user_guide.md
  src/functional/java/reposense/Entry.java
  src/functional/resources/expected/CS2103AUG2017-W09-B1_main/commits.json
  src/functional/resources/expected/CS2103AUG2017-W09-B2_main/commits.json
  src/functional/resources/expected/summary.json
  src/main/java/reposense/system/CommandRunner.java
  src/main/java/reposense/util/Constants.java
Labels: s.ToMerge
