Repository reposense/RepoSense, pull requests merged in 2018-06, with the labels that each got.

#126 Improve performance
  docs/developer_guide.md
  docs/user_guide.md
  src/functional/java/reposense/Entry.java
  src/main/java/reposense/git/GitBlamer.java
  src/main/java/reposense/system/CommandRunner.java
  src/main/java/reposense/system/StreamGobbler.java
  src/main/java/reposense/util/FileUtil.java
Labels: s.ToMerge

#123 Implement a logger
  .gitignore
  src/main/java/reposense/analyzer/CheckStyleParser.java
  src/main/java/reposense/analyzer/FileAnalyzer.java
  src/main/java/reposense/analyzer/FileInfoGenerator.java
  src/main/java/reposense/analyzer/MethodAnalyzer.java
  src/main/java/reposense/analyzer/RepoAnalyzer.java
  src/main/java/reposense/git/GitChecker.java
  src/main/java/reposense/git/GitCloner.java
  src/main/java/reposense/report/RepoInfoFileGenerator.java
  src/main/java/reposense/system/CustomLogFormatter.java
  src/main/java/reposense/system/LogsManager.java
  src/main/java/reposense/util/FileUtil.java
Labels: s.ToMerge

#142 Setup AppVeyor CI
  README.md
  appveyor.yml
Labels: s.ToReview

#145 Clean up the logger output #139
  src/main/java/reposense/system/CustomLogFormatter.java
Labels: s.ToReview

#144 Make Travis-CI test RepoSense on Mac OSX #143
  .travis.yml
Labels: s.ToReview

#136 Configure gradle to run with arguments #132
  build.gradle
  docs/user_guide.md
Labels: s.FinalReview

#130 Simplify CSV configuration file format #60 #138
  config.csv
  sample_full.csv
  sample_small.csv
  src/functional/java/reposense/Entry.java
  src/functional/resources/dateRange/expected/CS2103AUG2017-W09-B1_main/commits.json
  src/functional/resources/dateRange/expected/CS2103AUG2017-W09-B2_main/commits.json
  src/functional/resources/dateRange/expected/summary.json
  src/functional/resources/noDateRange/expected/CS2103AUG2017-W09-B1_main/commits.json
  src/functional/resources/noDateRange/expected/CS2103AUG2017-W09-B2_main/commits.json
  src/functional/resources/sample_full.csv
  src/main/java/reposense/analyzer/RepoAnalyzer.java
  src/main/java/reposense/dataobject/AuthorIntervalContribution.java
  src/main/java/reposense/dataobject/RepoConfiguration.java
  src/main/java/reposense/frontend/CliArguments.java
  src/main/java/reposense/frontend/RepoSense.java
  src/main/java/reposense/git/GitBlamer.java
  src/main/java/reposense/git/GitLogger.java
  src/main/java/reposense/parser/CsvParser.java
  src/main/java/reposense/report/ContributionSummaryGenerator.java
  src/main/java/reposense/system/CsvConfigurationBuilder.java
  src/main/java/reposense/util/Constants.java
  src/test/java/reposense/git/GitBlamerTest.java
  template/static/scripts/summaryVueMethods.js
  template/static/scripts/utils.js
Labels: s.ToMerge

#129 Simplify dashboard template for summary view
  docs/user_guide.md
  frontend/src/index.jade
  frontend/src/static/css/_colors.scss
  frontend/src/static/css/style.scss
  frontend/src/static/js/api.js
  frontend/src/static/js/main.js
  frontend/src/static/js/v_summary.js
  template/v2/index.html
  template/v2/static/css/_colors.css
  template/v2/static/css/style.css
  template/v2/static/js/api.js
  template/v2/static/js/main.js
  template/v2/static/js/v_summary.js
Labels: s.ToReview

#146 Cleanup user guide #140
  docs/images/rampchart.png
  docs/user_guide.md
Labels: s.ToMerge
