Repository reposense/RepoSense, pull requests merged in 2019-01, with the labels that each got.

#455 [#452] GitLogTest failure
  src/test/java/reposense/git/GitLogTest.java
Labels: s.FinalReview

#446 Make -view a flag to launch the report automatically after processing #315
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/model/CliArguments.java
  src/main/java/reposense/model/ConfigCliArguments.java
  src/main/java/reposense/model/LocationsCliArguments.java
  src/main/java/reposense/parser/ArgsParser.java
  src/test/java/reposense/parser/ArgsParserTest.java
Labels: s.ToMerge

#431 [Enhancement] Add args to ignore standalone config in command line #374
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/model/LocationsCliArguments.java
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/report/ReportGenerator.java
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/parser/RepoConfigurationTest.java
Labels: s.ToMerge

#448 CodeView: add selection to filter files by format #170
  docs/UserGuide.md
  docs/images/report.png
  frontend/src/index.jade
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_authorship.js
Labels: s.ToMerge

#472 Fix broken link on ramps #471
  frontend/src/static/js/v_summary.js
Labels: s.ToReview

#439 UserGuide: Update until example to -until 21/10/2017
  docs/UserGuide.md
Labels: s.ToMerge

#477 Fix mismatch of file content #473
  frontend/src/index.jade
Labels: s.ToReview

#441 [#350] [Enhancement] author-config.csv: make repo's location optional field
  docs/UserGuide.md
  src/main/java/reposense/model/Author.java
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/model/RepoLocation.java
  src/main/java/reposense/parser/AuthorConfigCsvParser.java
  src/test/java/reposense/commits/CommitInfoAnalyzerTest.java
  src/test/java/reposense/parser/CsvParserTest.java
  src/test/java/reposense/parser/RepoConfigurationTest.java
  src/test/java/reposense/util/TestUtil.java
  src/test/resources/CsvParserTest/authorconfig_emptyLocation_test.csv
  src/test/resources/CsvParserTest/repoconfig_merge_empty_location_test/author-config.csv
  src/test/resources/CsvParserTest/repoconfig_merge_empty_location_test/repo-config.csv
Labels: s.ToMerge

#475 Format and UserDoc: Add 'txt' format to default formats.
  docs/UserGuide.md
  src/main/java/reposense/model/Format.java
Labels: s.ToMerge

#495 Typing lag in the report search bar #373
  frontend/src/index.jade
  frontend/src/static/js/v_summary.js
Labels: s.ToReview

#494 User Guide: add FAQ section to address common problems #297
  docs/UserGuide.md
Labels: s.ToMerge

#505 Fix RuntimeException due to ambiguous argument in git rev-list #399
  src/main/java/reposense/git/GitRevList.java
Labels: s.ToReview

#490 Code view: give link to history and blame views of each file
  docs/UserGuide.md
  docs/diagrams/dashboard.pptx
  docs/diagrams/ug-report.pptx
  docs/images/dashboard.png
  docs/images/report.png
  frontend/src/index.jade
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_authorship.js
Labels: s.FinalReview

#478 Open dashboard with code-view shown
  frontend/src/index.jade
  frontend/src/static/js/main.js
Labels: s.ToMerge

#488 ChartView: apply case-insensitive sorting sequence to `Author Name` #501
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#497 Use Travis-CI to automate publishing of report to GitHub Pages #470
  docs/PublishingGuide.md
  docs/UserGuide.md
  docs/images/publishingguide-cronsetting.jpg
  docs/images/publishingguide-githubsetting.jpg
  docs/images/publishingguide-githubtoken.jpg
  docs/images/publishingguide-netlifypreview.png
  docs/images/publishingguide-travissetting.jpg
Labels: s.ToMerge

#511 [#380] Prevent generate FileInfo from directory with valid name
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
Labels: s.ToMerge

#498 Show a 'loading...' message while loading the report for the first time #392
  frontend/src/index.jade
  frontend/src/static/css/style.scss
  frontend/src/static/js/api.js
  frontend/src/static/js/main.js
Labels: s.ToMerge

#418 Make center divider adjustable #403
  frontend/src/index.jade
  frontend/src/static/css/style.scss
  frontend/src/static/js/main.js
Labels: s.ToMerge

#514 Enable ESLint JavaScript linter on travis #502
  .eslintrc.json
  .travis.yml
  frontend/.eslintrc.json
  frontend/src/static/js/api.js
  frontend/src/static/js/main.js
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_summary.js
Labels: s.Ongoing
