Repository reposense/RepoSense, pull requests merged in 2019-06, with the labels that each got.

#669 [#635] CodeView: add line number to code
  frontend/src/index.pug
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_authorship.js
Labels: s.ToMerge

#700 [#695] Report: allow reset of date controls
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#693 [#506] Report: add checks to ensure that .zip file is uploaded
  frontend/src/index.pug
  frontend/src/static/js/main.js
Labels: s.ToMerge

#704 [#702] Fix url directing to the wrong branch
  frontend/src/index.pug
  frontend/src/static/js/api.js
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#685 [#664] Toolbar: expand width for `breakdown by file format`
  frontend/src/static/css/style.scss
Labels: s.ToMerge

#679 [#678] Report: use development version of vue.js
  docs/DeveloperGuide.md
  docs/images/choose-vue.png
  docs/images/use-vue.png
  frontend/src/index.pug
Labels: s.ToMerge

#697 [#663] ChartView: add total contribution of group
  frontend/src/index.pug
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#668 [#647] Toolbar: rename values in `sort group by`
  frontend/src/index.pug
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#732 [#606] Enable use of deploy key for publishing
  docs/PublishingGuide.md
Labels: s.ToMerge

#670 [#660] ChartView: remove ramp slices not within date range
  frontend/src/ramp.pug
  frontend/src/static/js/v_ramp.js
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#715 [#712] ChartView: fix misalignment of chart title
  frontend/src/static/css/style.scss
Labels: s.ToMerge

#716 [#645] CodeView: improve UI of sort bar
  frontend/src/index.pug
  frontend/src/static/css/style.scss
Labels: s.FinalReview

#696 [#681] UG: Update UG in accordance to change in Toolbar
  docs/UserGuide.md
  docs/diagrams/report-features.pptx
  docs/images/report-features.png
Labels: s.ToReview

#730 [#720] Set command-click to activate zoom-in feature for macOS devices
  docs/UserGuide.md
  frontend/src/static/js/main.js
  frontend/src/static/js/v_ramp.js
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#766 [#721] Report: remove usage of spread operator
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#740 [#666] CodeView: load un-authored code only when toggled
  frontend/src/index.pug
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_segment.js
  frontend/src/tabs/segment.pug
Labels: s.ToMerge

#744 [#741] Fix view code icon not opening the CodeView
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#728 [#711] Analysis: ignore binary files
  docs/UserGuide.md
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/main/java/reposense/git/GitDiff.java
  src/main/java/reposense/git/GitUtil.java
  src/main/java/reposense/util/FileUtil.java
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
Labels: s.FinalReview

#742 [#680] Vue: fix error message in development mode
  frontend/src/index.pug
Labels: s.ToMerge
