Repository reposense/RepoSense, pull requests merged in 2019-08, with the labels that each got.

#743 [#598] Report: show error message summary
  build.gradle
  frontend/cypress/tests/chartView_errorSummary_messageBox.js
  frontend/src/index.pug
  frontend/src/static/css/style.scss
  frontend/src/static/js/api.js
  frontend/src/static/js/main.js
  frontend/src/static/js/v_summary.js
  src/main/java/reposense/report/ErrorSummary.java
  src/main/java/reposense/report/RepoCloner.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/report/SummaryJson.java
  src/systemtest/java/reposense/ConfigSystemTest.java
  src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Delta_nonExistentBranch/authorship.json
  src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Delta_nonExistentBranch/commits.json
  src/systemtest/resources/30daysFromUntilDate/expected/summary.json
  src/systemtest/resources/dateRange/expected/reposense_testrepo-Delta_nonExistentBranch/authorship.json
  src/systemtest/resources/dateRange/expected/reposense_testrepo-Delta_nonExistentBranch/commits.json
  src/systemtest/resources/dateRange/expected/summary.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Delta_nonExistentBranch/authorship.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Delta_nonExistentBranch/commits.json
  src/systemtest/resources/sinceBeginningDateRange/expected/summary.json
  src/test/java/reposense/report/RepoClonerTest.java
Labels: s.ToMerge

#775 [#767] Clear zoom region when settings change
  frontend/src/index.pug
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#843 [#319] Add unit test for minimal standalone config
  src/test/java/reposense/model/RepoConfigurationTest.java
Labels: s.ToMerge

#826 [#825] Zip: fix invalid report file directories being zipped
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/util/FileUtil.java
Labels: s.FinalReview

#848 Modify UI of zoom tab title
  frontend/src/index.pug
  frontend/src/static/css/style.scss
  frontend/src/tabs/zoom.pug
Labels: s.ToMerge

#755 [#750] Zoom Tab: display commit message body
  docs/UserGuide.md
  docs/images/commits-panel.png
  docs/images/opening-commits-panel.gif
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_zoom.js
  frontend/src/tabs/zoom.pug
Labels: s.ToMerge

#837 [#703] Log: show analysis progress
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/util/ProgressTracker.java
Labels: s.FinalReview

#822 [#808, #815] Docs: update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/report-features.pptx
  docs/diagrams/report-summary.pptx
  docs/images/rampchart.png
  docs/images/report-features.png
  docs/images/report-summary.png
  docs/images/vue-lifecycle-diagram.png
Labels: 24h, s.ToMerge

#824 [#817] Cypress: add code view loading time benchmark test
  frontend/cypress/cypress.json
  frontend/cypress/tests/codeView_load_benchmark.js
Labels: s.FinalReview

#854 [#851] Fix url directing to wrong repository when merge group
  frontend/src/static/js/v_ramp.js
  frontend/src/static/js/v_summary.js
  frontend/src/static/js/v_zoom.js
Labels: s.ToReview

#860 [#859] Improve logging message when repo (branch) isn't found in repo-config.csv
  src/main/java/reposense/model/AuthorConfiguration.java
  src/main/java/reposense/model/RepoConfiguration.java
Labels: s.FinalReview
