Repository reposense/RepoSense, pull requests merged in 2019-03, with the labels that each got.

#532 Code view: support glob filters
  build.gradle
  docs/UserGuide.md
  docs/diagrams/dashboard.pptx
  docs/diagrams/ug-report.pptx
  docs/images/dashboard.png
  docs/images/report.png
  frontend/src/index.jade
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_authorship.js
  package.json
Labels: p.High, s.ToMerge

#591 Non-linear ramp chart cause by invalid date range #585
  frontend/src/static/js/v_summary.js
Labels: s.ToReview

#582 README.md: add new team members
  README.md
Labels: s.ToMerge

#580 [#561] DashboardServer: Desktop#isDesktopSupported passes on headless systems
  src/main/java/reposense/system/DashboardServer.java
Labels: s.ToMerge

#593 Fix unoriented output messages
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/parser/ArgsParser.java
  src/systemtest/java/reposense/ConfigSystemTest.java
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/parser/CsvParserTest.java
  src/test/java/reposense/parser/RepoConfigurationTest.java
Labels: s.ToReview

#595 Cypress: front-end test failing due to timeouts
  frontend/cypress/cypress.json
Labels: s.ToMerge

#566 Refactor toolbar into v-authorship tab
  frontend/src/index.jade
  frontend/src/static/js/main.js
  frontend/src/static/js/v_authorship.js
Labels: s.ToMerge

#579 [#554] Rename 'dashboard' instances to 'report'
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/report-architecture.pptx
  docs/diagrams/report-screenshot.odg
  docs/diagrams/report-summary.pptx
  docs/images/report-architecture-authorship.png
  docs/images/report-architecture-summary.png
  docs/images/report-architecture.png
  docs/images/report-features.png
  docs/images/report-summary.png
  frontend/src/static/js/api.js
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/report/SummaryReportJson.java
  src/main/java/reposense/system/ReportServer.java
  src/systemtest/resources/dateRange/expected/summary.json
  src/systemtest/resources/noDateRange/expected/summary.json
Labels: s.ToMerge

#560 Perform cloning in parallel with analyzing #540
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/main/java/reposense/git/GitCheckout.java
  src/main/java/reposense/git/GitClone.java
  src/main/java/reposense/git/exception/CommitNotFoundException.java
  src/main/java/reposense/git/exception/GitCloneException.java
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/report/RepoCloner.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/system/CommandRunner.java
  src/main/java/reposense/system/CommandRunnerProcess.java
  src/main/java/reposense/system/CommandRunnerProcessException.java
  src/test/java/reposense/authorship/FileAnalyzerTest.java
  src/test/java/reposense/git/GitBranchTest.java
  src/test/java/reposense/git/GitCheckoutTest.java
  src/test/java/reposense/git/GitCloneTest.java
  src/test/java/reposense/parser/RepoConfigurationTest.java
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.ToMerge

#524 [#465] Bookmark codeview uri
  docs/UserGuide.md
  frontend/src/index.jade
  frontend/src/static/js/main.js
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#445 [#407] CodeView: give additional sorting options
  frontend/src/index.jade
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#612 Add default title and icon for generated report
  frontend/src/favicon.ico
  frontend/src/index.jade
Labels: s.ToMerge

#570 RampChart: add group by authors option
  frontend/src/index.jade
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#496 [#459] CLI: add args to choose any timezone
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/model/CliArguments.java
  src/main/java/reposense/model/ConfigCliArguments.java
  src/main/java/reposense/model/LocationsCliArguments.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/parser/ZoneIdArgumentType.java
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/util/InputBuilder.java
Labels: s.ToMerge

#589 [#588] CodeView: align the checkboxes
  frontend/src/index.jade
  frontend/src/static/css/style.scss
Labels: s.ToMerge

#623 CsvParser#parse: fix error handling of `processLine` #622
  src/main/java/reposense/parser/CsvParser.java
  src/test/java/reposense/parser/CsvParserTest.java
  src/test/resources/CsvParserTest/authorconfig_invalidLocation_test.csv
Labels: s.ToMerge

#620 [#600] Integrate Coverage Test
  .travis.yml
  README.md
  build.gradle
Labels: s.FinalReview

#628 [#619] Remove Unused Class in Main Code
  src/main/java/reposense/authorship/analyzer/MethodAnalyzer.java
  src/main/java/reposense/authorship/model/MethodInfo.java
  src/main/java/reposense/builder/ConfigurationBuilder.java
Labels: s.ToReview

#629 RepoConfigurationTest: move to reposense.model
  src/test/java/reposense/model/RepoConfigurationTest.java
Labels: s.ToReview

#631 Remove Codecov robot comment
  codecov.yml
Labels: s.ToReview

#602 Allow overriding of values from StandaloneConfig by repo-config.csv #390
  docs/UserGuide.md
  repo-config.csv
  src/main/java/reposense/model/AuthorConfiguration.java
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/parser/CsvParser.java
  src/main/java/reposense/parser/RepoConfigCsvParser.java
  src/test/java/reposense/model/RepoConfigurationTest.java
  src/test/java/reposense/parser/CsvParserTest.java
  src/test/resources/CsvParserTest/repoconfig_overrideKeyword_test.csv
  src/test/resources/RepoConfigurationTest/repoconfig_overrideStandAlone_test/repo-config.csv
Labels: s.ToReview

#611 [#599] CodeView: fix `All` checkbox indication failure
  frontend/src/static/js/v_authorship.js
Labels: s.ToMerge

#608 [#581] CodeView#filter: add interactive selection switch
  frontend/src/index.jade
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_authorship.js
Labels: s.ToMerge

#616 Console output: make logs clearer after cloning in parallel #609
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/main/java/reposense/commits/CommitInfoAnalyzer.java
  src/main/java/reposense/commits/CommitInfoExtractor.java
  src/main/java/reposense/report/RepoCloner.java
  src/main/java/reposense/report/ReportGenerator.java
Labels: s.ToMerge
