Repository reposense/RepoSense, pull requests merged in 2019-04, with the labels that each got.

#596 Page unresponsive when loading report of many repos with huge date gap #542
  frontend/src/index.jade
  frontend/src/static/js/api.js
  frontend/src/static/js/v_summary.js
  src/main/java/reposense/commits/CommitResultAggregator.java
  src/systemtest/resources/dateRange/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/dateRange/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/dateRange/expected/reposense_testrepo-Delta_master/commits.json
  src/systemtest/resources/noDateRange/expected/reposense_testrepo-Alpha_master/commits.json
  src/systemtest/resources/noDateRange/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/noDateRange/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/noDateRange/expected/reposense_testrepo-Delta_master/commits.json
Labels: s.ToMerge

#617 author-config#email: include + operator infinite email matcher #613
  src/main/java/reposense/authorship/FileInfoAnalyzer.java
  src/main/java/reposense/commits/CommitInfoAnalyzer.java
  src/main/java/reposense/git/GitUtil.java
  src/main/java/reposense/model/AuthorConfiguration.java
  src/main/java/reposense/model/RepoConfiguration.java
  src/test/java/reposense/authorship/FileAnalyzerTest.java
  src/test/java/reposense/commits/CommitInfoAnalyzerTest.java
  src/test/java/reposense/git/GitLogTest.java
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.ToMerge

#592 GitLog: handle paths in config that exist outside the repo [#398]
  src/main/java/reposense/git/GitLog.java
  src/main/java/reposense/git/GitUtil.java
  src/test/java/reposense/git/GitLogTest.java
  src/test/java/reposense/git/GitUtilTest.java
  src/test/java/reposense/util/TestUtil.java
Labels: s.ToMerge

#564 GitLsTree: validate filepaths before cloning #391
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/main/java/reposense/authorship/model/FileInfo.java
  src/main/java/reposense/git/GitClone.java
  src/main/java/reposense/git/GitLsTree.java
  src/main/java/reposense/git/exception/InvalidFilePathException.java
  src/main/java/reposense/report/RepoCloner.java
  src/main/java/reposense/system/CommandRunner.java
  src/main/java/reposense/util/StringsUtil.java
  src/main/java/reposense/util/SystemUtil.java
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
  src/test/java/reposense/git/GitLsTreeTest.java
Labels: s.ToMerge

#618 Redesigning the sorting toolbar
  frontend/src/index.jade
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_summary.js
Labels: s.FinalReview

#575 WIP: Implementing the zoomin tab
  frontend/src/index.pug
  frontend/src/ramp.pug
  frontend/src/static/css/style.scss
  frontend/src/static/js/main.js
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_ramp.js
  frontend/src/static/js/v_summary.js
  frontend/src/static/js/v_zoomin.js
  frontend/src/zoomin.pug
Labels: s.ToReview

#626 Checkstyle: increase severity of all existing rules #624
  config/checkstyle/checkstyle.xml
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/authorship/analyzer/AnnotatorAnalyzer.java
  src/main/java/reposense/commits/CommitResultAggregator.java
  src/main/java/reposense/git/GitClone.java
  src/main/java/reposense/git/exception/GitCloneException.java
  src/main/java/reposense/model/Author.java
  src/main/java/reposense/model/AuthorConfiguration.java
  src/main/java/reposense/model/ConfigCliArguments.java
  src/main/java/reposense/model/LocationsCliArguments.java
  src/main/java/reposense/model/ViewCliArguments.java
  src/main/java/reposense/parser/AuthorConfigCsvParser.java
  src/main/java/reposense/parser/ConfigFolderArgumentType.java
  src/main/java/reposense/parser/CsvParser.java
  src/main/java/reposense/parser/OutputFolderArgumentType.java
  src/main/java/reposense/parser/ParseException.java
  src/main/java/reposense/parser/RepoConfigCsvParser.java
  src/main/java/reposense/parser/ReportFolderArgumentType.java
  src/main/java/reposense/report/RepoCloner.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/system/CommandRunner.java
  src/main/java/reposense/system/LogsManager.java
  src/main/java/reposense/system/StreamGobbler.java
  src/main/java/reposense/util/FileUtil.java
  src/main/java/reposense/util/SystemUtil.java
  src/systemtest/java/reposense/ConfigSystemTest.java
  src/test/java/reposense/model/RepoConfigurationTest.java
  src/test/java/reposense/model/StandaloneConfigTest.java
  src/test/java/reposense/parser/StandaloneConfigJsonParserTest.java
  src/test/java/reposense/template/GitTestTemplate.java
  src/test/java/reposense/util/TestUtil.java
Labels: s.ToMerge

#539 RampChart: show up to report generation date, not last commit date #518
  frontend/src/static/js/api.js
  frontend/src/static/js/v_summary.js
  src/main/java/reposense/model/RepoConfiguration.java
  src/systemtest/java/reposense/ConfigSystemTest.java
  src/systemtest/resources/noDateRange/expected/summary.json
Labels: s.ToMerge

#615 summary.json: move sinceDate and untilDate become direct element #607
  frontend/src/static/js/api.js
  frontend/src/static/js/v_summary.js
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/commits/CommitResultAggregator.java
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/report/SummaryReportJson.java
  src/systemtest/java/reposense/ConfigSystemTest.java
  src/systemtest/resources/dateRange/expected/summary.json
  src/systemtest/resources/noDateRange/expected/summary.json
Labels: s.ToMerge

#565 [#503] CLI: add --version tag to show version of RepoSense
  .travis.yml
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  frontend/src/index.jade
  frontend/src/static/js/api.js
  frontend/src/static/js/main.js
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/report/SummaryReportJson.java
Labels: s.ToMerge

#641 GitLog: update to use commit date instead of author date #640
  src/main/java/reposense/git/GitLog.java
  src/systemtest/resources/noDateRange/expected/reposense_testrepo-Charlie_master/commits.json
Labels: s.ToMerge

#650 .travis.yml: change oraclejdk8 to openjdk8
  .travis.yml
Labels: s.ToMerge

#632 [#621] LogsManager: shift the log file to output folder
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/system/LogsManager.java
  src/main/java/reposense/util/FileUtil.java
  src/test/java/reposense/parser/ArgsParserTest.java
Labels: s.ToMerge

#638 ContributionBar: length changes on breakdown option selected #637
  frontend/cypress/tests/contributionBar.js
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge
