Repository reposense/RepoSense, pull requests merged in 2019-07, with the labels that each got.

#782 [#781] Fix broken program when reserved character is used without escaping
  docs/UserGuide.md
  src/main/java/reposense/parser/SinceDateArgumentType.java
  src/systemtest/java/reposense/ConfigSystemTest.java
Labels: s.ToMerge

#777 [#770] Add placeholder for repositories with no author commits
  src/main/java/reposense/model/Author.java
  src/main/java/reposense/report/CommitReportJson.java
  src/main/java/reposense/report/RepoCloner.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/report/exception/NoAuthorsWithCommitsFoundException.java
  src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Alpha_master/commits.json
  src/systemtest/resources/dateRange/expected/reposense_testrepo-Alpha_master/commits.json
Labels: s.ToMerge

#773 [#312] CodeView: reduce space taken by toggle icon
  docs/diagrams/report-features.pptx
  docs/images/report-features.png
  frontend/src/static/css/style.scss
  frontend/src/tabs/segment.pug
Labels: s.ToMerge

#768 [#745] Toolbar: edit flexbox properties
  frontend/src/index.pug
  frontend/src/static/css/style.scss
Labels: s.FinalReview

#749 [#748] Restore authorship tab
  frontend/src/static/js/main.js
  frontend/src/static/js/v_authorship.js
Labels: s.FinalReview

#656 [#567] Zip: prevent unrelated files and/or folders from getting zipped
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/report/SummaryJson.java
  src/main/java/reposense/util/FileUtil.java
  src/test/java/reposense/util/FileUtilTest.java
  src/test/resources/FileUtilTest/expectedRelevantUnzippedFiles/reposense_testrepo-Beta/authorship.json
  src/test/resources/FileUtilTest/expectedRelevantUnzippedFiles/reposense_testrepo-Beta/commits.json
  src/test/resources/FileUtilTest/expectedRelevantUnzippedFiles/reposense_testrepo-Charlie/authorship.json
  src/test/resources/FileUtilTest/expectedRelevantUnzippedFiles/reposense_testrepo-Charlie/commits.json
  src/test/resources/FileUtilTest/expectedRelevantUnzippedFiles/summary.json
  src/test/resources/FileUtilTest/reposense-report-test/someUnrelatedFile.json
  src/test/resources/FileUtilTest/reposense-report-test/someUnrelatedFolder/somemoreUnrelatedFile.json
Labels: s.ToReview

#794 [#705] Log: distinct warning and error messages
  build.gradle
  src/main/java/reposense/system/CustomLogFormatter.java
Labels: s.ToMerge

#792 [#791] CodeView: bugfix for unexpected colors in line numbers
  frontend/src/static/css/style.scss
Labels: s.ToMerge

#739 [#738] CsvParser: fix incorrect splitting of literals commas
  build.gradle
  src/main/java/reposense/parser/AuthorConfigCsvParser.java
  src/main/java/reposense/parser/CsvParser.java
  src/main/java/reposense/parser/RepoConfigCsvParser.java
  src/test/java/reposense/parser/CsvParserTest.java
  src/test/resources/CsvParserTest/authorconfig_commasAndDoubleQuotes_test.csv
  src/test/resources/CsvParserTest/repoconfig_merge_empty_location_test/repo-config.csv
  src/test/resources/repoconfig_merge_test/repo-config.csv
Labels: s.ToMerge

#708 [#531,#707] Analysis: use all formats by default
  docs/DeveloperGuide.md
  docs/UserGuide.md
  frontend/src/index.pug
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_summary.js
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/main/java/reposense/authorship/model/AuthorshipSummary.java
  src/main/java/reposense/model/Format.java
  src/main/java/reposense/model/StandaloneConfig.java
  src/main/java/reposense/parser/ArgsParser.java
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
  src/test/java/reposense/git/GitBranchTest.java
  src/test/java/reposense/model/FormatTest.java
  src/test/java/reposense/model/RepoConfigurationTest.java
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/parser/StandaloneConfigJsonParserTest.java
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.ToMerge

#790 ChartView: modify UI of placeholder for repositories with no author commits
  frontend/src/index.pug
  frontend/src/static/css/style.scss
Labels: s.FinalReview

#813 [#811] Fix position of toggle icons
  frontend/src/static/css/style.scss
Labels: s.FinalReview

#762 [#753] Display contribution per chart
  frontend/src/index.pug
  frontend/src/static/css/style.scss
Labels: s.ToMerge

#803 [#522] Implement style checker on .scss files
  .stylelintrc.json
  .travis.yml
  docs/DeveloperGuide.md
  frontend/src/static/css/_colors.scss
  frontend/src/static/css/style.scss
  package.json
Labels: s.ToReview

#802 [#661] Change chart title format
  docs/UserGuide.md
  frontend/src/static/js/api.js
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/report/RepoCloner.java
  src/main/java/reposense/report/ReportGenerator.java
  src/systemtest/resources/30daysFromUntilDate/expected/summary.json
  src/systemtest/resources/dateRange/expected/summary.json
  src/systemtest/resources/sinceBeginningDateRange/expected/summary.json
Labels: s.ToMerge

#797 [#764] Toolbar: fix bug of Safari browser unable to activate search functionality
  frontend/src/index.pug
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#800 [#763] v_summary.js: ensure getFiltered() is only called once when reloading page
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#729 [#724] Modify zoom-in feature based on selected granularity
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_summary.js
  frontend/src/static/js/v_zoom.js
  frontend/src/tabs/zoom.pug
Labels: s.ToMerge

#783 [#780] v_summary.js: remove Vue watcher for repos
  frontend/src/index.pug
  frontend/src/static/js/main.js
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#821 [#820] Update sample report used in Cypress tests
  build.gradle
Labels: s.ToMerge

#751 CommitInfo: capture commits' message body
  frontend/src/ramp.pug
  frontend/src/tabs/zoom.pug
  src/main/java/reposense/commits/CommitInfoAnalyzer.java
  src/main/java/reposense/commits/CommitInfoExtractor.java
  src/main/java/reposense/commits/model/CommitResult.java
  src/main/java/reposense/git/GitLog.java
  src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/dateRange/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/dateRange/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Alpha_master/commits.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Delta_master/commits.json
  src/test/java/reposense/commits/CommitInfoAnalyzerTest.java
  src/test/java/reposense/template/GitTestTemplate.java
  src/test/java/reposense/util/TestUtil.java
Labels: s.ToMerge

#832 [#828] Revert PR #800
  frontend/src/static/js/v_summary.js
Labels: s.ToReview

#836 [#833] build.gradle: update node.js to 10.16.0
  build.gradle
Labels: s.ToReview

#810 [#809] Update HTML report section in DG
  docs/DeveloperGuide.md
  docs/diagrams/report-architecture.pptx
  docs/diagrams/report-summary.pptx
  docs/images/report-architecture-authorship.png
  docs/images/report-architecture-summary.png
  docs/images/report-architecture.png
  docs/images/report-summary.png
  docs/images/vue-lifecycle-diagram.png
Labels: 48h, s.FinalReview

#801 [#723] Fix bug of Safari browser not able to modify sinceDate and untilDate
  frontend/src/index.pug
  frontend/src/static/js/safari_date.js
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#796 [#778] Add button that opens zoom tab for the entire ramp chart
  frontend/src/index.pug
  frontend/src/static/js/v_summary.js
Labels: s.FinalReview

#765 [#759] Cloning: prevent double cloning of the same repo from remote
  docs/DeveloperGuide.md
  src/main/java/reposense/git/GitClone.java
  src/main/java/reposense/git/GitLsTree.java
  src/main/java/reposense/git/GitRevParse.java
  src/main/java/reposense/report/RepoCloner.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/util/FileUtil.java
  src/test/java/reposense/git/GitLsTreeTest.java
  src/test/java/reposense/git/GitRevParseTest.java
  src/test/java/reposense/report/RepoClonerTest.java
Labels: s.ToMerge

#752 [#662] Add merge group option
  frontend/src/index.pug
  frontend/src/ramp.pug
  frontend/src/static/js/v_ramp.js
  frontend/src/static/js/v_summary.js
  frontend/src/tabs/zoom.pug
Labels: s.FinalReview

#847 [#846] Fix bug of show ramps for this period button only works once
  frontend/src/static/js/main.js
  frontend/src/static/js/v_summary.js
  frontend/src/static/js/v_zoom.js
Labels: s.ToReview

#840 [#839] Set config to be inclusive of until date
  docs/UserGuide.md
  src/main/java/reposense/git/GitUtil.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/parser/DateArgumentType.java
  src/main/java/reposense/parser/SinceDateArgumentType.java
  src/main/java/reposense/parser/UntilDateArgumentType.java
  src/test/java/reposense/authorship/FileAnalyzerTest.java
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
  src/test/java/reposense/commits/CommitInfoExtractorTest.java
  src/test/java/reposense/git/GitCheckoutTest.java
  src/test/java/reposense/git/GitLogTest.java
  src/test/java/reposense/git/GitRevListTest.java
  src/test/java/reposense/git/GitShortlogTest.java
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/util/TestUtil.java
Labels: s.ToMerge

#757 [#754] Url: include date hashes only when modified
  frontend/src/index.pug
  frontend/src/static/js/api.js
  frontend/src/static/js/v_summary.js
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/model/CliArguments.java
  src/main/java/reposense/model/ConfigCliArguments.java
  src/main/java/reposense/model/LocationsCliArguments.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/report/SummaryJson.java
  src/systemtest/java/reposense/ConfigSystemTest.java
  src/systemtest/resources/30daysFromUntilDate/expected/summary.json
  src/systemtest/resources/dateRange/expected/summary.json
  src/systemtest/resources/sinceBeginningDateRange/expected/summary.json
Labels: s.FinalReview

#844 [#842] Fix out of bound ramp slices
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge
