Repository reposense/RepoSense, pull requests merged in 2020-02, with the labels that each got.

#1030 [#1029] Add float left property to contribution bar
  frontend/src/static/css/v_summary.scss
Labels: s.ToReview

#983 [#964] Add UG link to report page
  README.md
  frontend/src/index.pug
  frontend/src/static/js/main.js
Labels: s.ToMerge

#1036 [#1032] Author: fix error in copy constructor
  src/main/java/reposense/model/Author.java
Labels: s.ToMerge

#1017 [#873, #1016, #1049]Enable octocat icon for merge group and fix thickness of contribution bars
  frontend/cypress/tests/codeView_load_benchmark.js
  frontend/src/index.pug
  frontend/src/static/css/v_summary.scss
  frontend/src/static/js/v_summary.js
Labels: s.ToReview

#1020 [#1019] Handle commit info extraction for empty commits
  src/main/java/reposense/commits/CommitInfoAnalyzer.java
  src/main/java/reposense/commits/CommitInfoExtractor.java
  src/main/java/reposense/git/GitLog.java
  src/test/java/reposense/commits/CommitInfoAnalyzerTest.java
Labels: s.ToMerge

#1028 [#1027] Modify UI for tags
  frontend/src/static/css/style.scss
Labels: s.ToMerge

#922 [#920] Ramp chart: show percentile for each item
  docs/UserGuide.md
  docs/diagrams/report-features.pptx
  docs/images/rampchart.png
  docs/images/report-features.png
  frontend/src/index.pug
  frontend/src/static/css/v_summary.scss
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#916 [#942] CsvParser: Improve exception handling when csv config has no valid configs
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/parser/CsvParser.java
  src/systemtest/java/reposense/ConfigSystemTest.java
  src/test/java/reposense/model/RepoConfigurationTest.java
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/parser/AuthorConfigParserTest.java
  src/test/java/reposense/parser/GroupConfigParserTest.java
  src/test/java/reposense/parser/RepoConfigParserTest.java
  src/test/resources/CsvParserTest/repoconfig_zeroValidRecords_test.csv
Labels: s.ToMerge

#943 [#838] ZoomTab: add sort controls
  docs/UserGuide.md
  docs/images/commits-panel.png
  docs/images/opening-commits-panel.gif
  frontend/src/static/css/style.scss
  frontend/src/static/css/v_authorship.scss
  frontend/src/static/js/v_zoom.js
  frontend/src/tabs/authorship.pug
  frontend/src/tabs/zoom.pug
Labels: s.FinalReview

#1033 [#1021]: Use BASE_URL constant instead of string
  frontend/src/static/js/main.js
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_ramp.js
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#1055 [#960] Refactor Ramp css
  frontend/src/index.pug
  frontend/src/static/css/style.scss
  frontend/src/static/css/v_ramp.scss
Labels: s.ToMerge

#1034 [#1031] Commits panel: ramp appears outside row
  frontend/src/static/css/v_ramp.scss
Labels: s.ToMerge

#1039 [#1022] FileInfoAnalyzer: Deprecate "//@reused" tag
  src/main/java/reposense/authorship/FileInfoAnalyzer.java
  src/main/java/reposense/util/FileUtil.java
Labels: s.ToMerge

#987 [#522] Implement style checker on .pug files
  .pug-lintrc.json
  frontend/src/index.pug
  frontend/src/ramp.pug
  frontend/src/tabs/authorship.pug
  frontend/src/tabs/zoom.pug
  package.json
Labels: s.FinalReview

#1000 [#999] Remove empty zoom__day divs
  frontend/src/static/js/v_summary.js
  frontend/src/static/js/v_zoom.js
  frontend/src/tabs/zoom.pug
Labels: s.ToMerge

#972 [#941] GitLsTree: modify regex to capture all windows reserved characters
  src/main/java/reposense/git/GitLsTree.java
  src/test/java/reposense/git/GitLsTreeTest.java
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.ToMerge

#907 [#906,#994,#1006] UserGuide: update doc and remove errors
  docs/UserGuide.md
Labels: s.ToMerge

#1040 [#1023] Authorship Panel: expand all button always appear when first open the page
  frontend/src/static/js/v_authorship.js
  frontend/src/tabs/authorship.pug
Labels: s.ToMerge

#1075 [#1071] Zoom view: provide a way to highlight the commit
  docs/UserGuide.md
  docs/images/commits-panel.png
  docs/images/opening-commits-panel.gif
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_zoom.js
  frontend/src/tabs/zoom.pug
Labels: s.ToMerge

#1062 [#576] Refactor summary from index
  frontend/src/index.pug
  frontend/src/summary.pug
Labels: s.ToMerge

#1045 [#1043] Fix bug of incorrect commit dates when merge group
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#1074 [#947] Authorship view: update sort controls
  frontend/src/static/js/v_authorship.js
Labels: s.ToMerge

#1079 [#960] Refactor Zoom css
  frontend/src/index.pug
  frontend/src/static/css/style.scss
  frontend/src/static/css/v_zoom.scss
Labels: s.ToMerge
