Repository reposense/RepoSense, pull requests merged in 2020-11, with the labels that each got.

#1325 [#1293] Fix case types in documentation
  docs/dg/report.md
  docs/ug/usingReports.md
Labels: s.ToMerge

#1347 [#1336] Show non-blank line count in the brackets instead of blank lines
  docs/images/code-panel.png
  docs/ug/usingReports.md
  frontend/src/tabs/authorship.pug
Labels: 48h, s.ToMerge

#1343 [#590] Configuring report generation
  build.gradle
  docs/ug/cli.md
  docs/ug/configFiles.md
  docs/ug/report-config.json
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/model/CliArguments.java
  src/main/java/reposense/model/ConfigCliArguments.java
  src/main/java/reposense/model/LocationsCliArguments.java
  src/main/java/reposense/model/ReportConfiguration.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/parser/AssetsFolderArgumentType.java
  src/main/java/reposense/parser/ReportConfigJsonParser.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/report/SummaryJson.java
  src/main/java/reposense/util/FileUtil.java
  src/systemtest/java/reposense/ConfigSystemTest.java
  src/systemtest/resources/30daysFromUntilDate/expected/summary.json
  src/systemtest/resources/dateRange/expected/summary.json
  src/systemtest/resources/report-config.json
  src/systemtest/resources/sinceBeginningDateRange/expected/summary.json
  src/test/java/reposense/parser/ReportConfigJsonParserTest.java
  src/test/resources/ReportConfigJsonParserTest/report-config-empty.json
  src/test/resources/ReportConfigJsonParserTest/report-config-invalid.json
  src/test/resources/ReportConfigJsonParserTest/report-config-valid.json
Labels: s.ToMerge

#1346 [#816] Generate the report based on the user's timezone
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/authorship/FileInfoAnalyzer.java
  src/main/java/reposense/commits/CommitResultAggregator.java
  src/main/java/reposense/git/GitUtil.java
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/report/SummaryJson.java
  src/systemtest/java/reposense/ConfigSystemTest.java
  src/systemtest/resources/30daysFromUntilDate/expected/summary.json
  src/systemtest/resources/dateRange/expected/summary.json
  src/systemtest/resources/sinceBeginningDateRange/expected/summary.json
  src/test/java/reposense/authorship/AnnotatorAnalyzerTest.java
  src/test/java/reposense/authorship/FileAnalyzerTest.java
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/template/GitTestTemplate.java
  src/test/java/reposense/util/TestUtil.java
Labels: 48h, s.ToMerge

#1318 [#1276] Delay execution of filterGroupSelection watcher
  frontend/src/static/js/v_summary.js
Labels: 48h, s.ToMerge

#1355 [#1341] Hash sort order in commits panel
  frontend/cypress/tests/zoomView/zoomView_reload.js
  frontend/src/static/js/v_zoom.js
Labels: s.ToReview

#1353 [#1344] Remove unused variable isFileTypesLoaded
  frontend/src/static/js/v_zoom.js
Labels: s.ToMerge
