Repository reposense/RepoSense, pull requests merged in 2020-09, with the labels that each got.

#1323 [#1128] Remove setting of file format in BeforeClass method of GitTestTemplate
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.ToMerge

#1324 [#1205] Provide more information on the landing page
  frontend/cypress/tests/codeView/codeView.js
  frontend/src/index.pug
  frontend/src/static/js/main.js
Labels: s.FinalReview

#1320 Store fileTypeColors as Vuex global variable
  frontend/src/static/js/store.js
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_summary.js
  frontend/src/static/js/v_summary_charts.js
  frontend/src/summary.pug
  frontend/src/tabs/authorship.pug
Labels: s.ToMerge

#1101 [#155] Display date ranged commit in side bar
  frontend/src/ramp.pug
  frontend/src/static/js/main.js
  frontend/src/static/js/v_ramp.js
  frontend/src/static/js/v_summary.js
  frontend/src/static/js/v_summary_charts.js
  frontend/src/static/js/v_zoom.js
  frontend/src/summary_charts.pug
  frontend/src/tabs/zoom.pug
Labels: s.ToMerge

#1330 [#1329] FileInfoExtractor: Add check for optional quotes in diff file regex
  src/main/java/reposense/authorship/FileInfoExtractor.java
Labels: s.ToMerge

#1332 [#1328] Fix usage of non-existent delimiter
  frontend/src/static/js/v_authorship.js
Labels: s.ToMerge

#1334 [#1322] Fix loading page rendering issue
  frontend/src/index.pug
  frontend/src/static/js/main.js
Labels: s.ToReview
