Repository reposense/RepoSense, pull requests merged in 2020-10, with the labels that each got.

#1337 [#1312] Conditional run for markbind to gh pages deployment
  .travis.yml
Labels: s.ToReview

#1335 [#1333] Fix loading of local reports
  frontend/src/static/js/main.js
Labels: s.ToMerge

#1310 [#1220] Add frontend tests
  frontend/cypress/.eslintrc.json
  frontend/cypress/tests/codeView/codeView_checkFileTypes.js
  frontend/cypress/tests/codeView/codeView_hideFileDetails.js
  frontend/cypress/tests/codeView/codeView_reload.js
  frontend/cypress/tests/zoomView/zoomView_hideCommitMessages.js
  frontend/cypress/tests/zoomView/zoomView_reload.js
  frontend/src/static/css/v_zoom.scss
  frontend/src/tabs/authorship.pug
  frontend/src/tabs/zoom.pug
Labels: s.ToReview

#1326 [#1239] Add filetype tags in commits panel
  frontend/cypress/tests/zoomView/zoomView_reload.js
  frontend/cypress/tests/zoomView/zoomView_selectFileTypes.js
  frontend/src/static/css/panels.scss
  frontend/src/static/css/v_authorship.scss
  frontend/src/static/js/v_summary.js
  frontend/src/static/js/v_summary_charts.js
  frontend/src/static/js/v_zoom.js
  frontend/src/tabs/zoom.pug
Labels: 48h, s.ToMerge

#1331 [#1205] Show a tooltip when hovering over ambiguous icons and text
  frontend/src/static/css/_z-indices.scss
  frontend/src/static/css/style.scss
  frontend/src/static/css/v_summary.scss
  frontend/src/summary_charts.pug
  frontend/src/tabs/authorship.pug
  frontend/src/tabs/zoom.pug
Labels: s.FinalReview
