Repository reposense/RepoSense, pull requests merged in 2020-08, with the labels that each got.

#1280 [#1279] Provide a way to run analysis for a moving window
  docs/ug/cli.md
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/parser/PeriodArgumentType.java
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/util/InputBuilder.java
Labels: s.ToMerge

#1299 Github Action for Closing Stale PRs
  .github/workflows/stale.yml
Labels: s.ToReview

#1269 [#1240] Remove insertion and deletion of each commit in commits.json
  frontend/src/static/js/api.js
  frontend/src/static/js/v_summary.js
  frontend/src/static/js/v_summary_charts.js
  frontend/src/summary_charts.pug
  frontend/src/tabs/authorship.pug
  src/main/java/reposense/authorship/model/AuthorshipSummary.java
  src/main/java/reposense/commits/model/AuthorDailyContribution.java
  src/main/java/reposense/report/CommitReportJson.java
  src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Alpha_master/commits.json
  src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Delta_master/commits.json
  src/systemtest/resources/dateRange/expected/reposense_testrepo-Alpha_master/commits.json
  src/systemtest/resources/dateRange/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/dateRange/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/dateRange/expected/reposense_testrepo-Delta_master/commits.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Alpha_master/commits.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Delta_master/commits.json
Labels: s.ToMerge

#1264 [#1263] Tests: Simplify resource loading
  src/systemtest/java/reposense/ConfigSystemTest.java
  src/test/java/reposense/model/RepoConfigurationTest.java
  src/test/java/reposense/model/StandaloneConfigTest.java
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/parser/AuthorConfigParserTest.java
  src/test/java/reposense/parser/GroupConfigParserTest.java
  src/test/java/reposense/parser/RepoConfigParserTest.java
  src/test/java/reposense/parser/StandaloneConfigJsonParserTest.java
  src/test/java/reposense/util/FileUtilTest.java
  src/test/java/reposense/util/StringsUtilTest.java
  src/test/java/reposense/util/TestUtil.java
Labels: s.ToMerge

#1313 [#1204] AuthorConfiguration#resetAuthorInformation can be made more readable
  src/main/java/reposense/model/AuthorConfiguration.java
  src/main/java/reposense/model/RepoConfiguration.java
Labels: s.FinalReview

#1157 [#1129] RepoSense: exit gracefully when all repo locations are invalid
  src/main/java/reposense/RepoSense.java
  src/test/java/reposense/parser/ArgsParserTest.java
Labels: s.FinalReview

#1314 [#1251] Change file type label font weight
  frontend/src/static/css/v_authorship.scss
Labels: s.ToMerge

#1315 [#1282] Remove trailing whitespace in issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/documentation.md
Labels: s.ToMerge

#1305 [#1232] Fix footer link
  frontend/src/index.pug
  frontend/src/static/js/api.js
  frontend/src/static/js/main.js
Labels: s.ToMerge

#1317 [#938] Fix inaccurate Javadoc comment
  src/main/java/reposense/model/RepoConfiguration.java
Labels: s.ToMerge

#1321 [#1111] Specify HTML doctype for report
  frontend/src/index.pug
Labels: s.ToMerge

#1270 [#1257] AuthorConfigCsvParser: Initialize author fully before adding to config
  src/main/java/reposense/parser/AuthorConfigCsvParser.java
Labels: s.ToMerge
