Repository reposense/RepoSense, pull requests merged in 2020-01, with the labels that each got.

#955 [#872] CsvParser: improve exception handling when a csv file has incorrect number of columns in header
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/parser/AuthorConfigCsvParser.java
  src/main/java/reposense/parser/CsvParser.java
  src/main/java/reposense/parser/GroupConfigCsvParser.java
  src/main/java/reposense/parser/RepoConfigCsvParser.java
  src/test/java/reposense/parser/CsvParserTest.java
  src/test/resources/CsvParserTest/authorconfig_invalidHeaderSize_test.csv
  src/test/resources/CsvParserTest/groupconfig_invalidHeaderSize_test.csv
  src/test/resources/CsvParserTest/repoconfig_invalidHeaderSize_test.csv
Labels: s.ToMerge

#973 SystemTest: Delete ft_temp folder after test
  src/systemtest/java/reposense/ConfigSystemTest.java
Labels: s.ToMerge

#971 [#852] Zoom tab displays commits not within filter time rage
  frontend/src/static/js/v_summary.js
  frontend/src/static/js/v_zoom.js
  frontend/src/tabs/zoom.pug
Labels: s.ToMerge

#948 [#947]Synchronising different tab views
  frontend/src/index.pug
  frontend/src/static/js/v_summary.js
  frontend/src/tabs/authorship.pug
  frontend/src/tabs/zoom.pug
Labels: s.ToMerge

#990 [#980] Date in url adapted without validation
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#963 CsvParserTest: Refactor CsvParserTest into author, group and repo config parser tests
  src/test/java/reposense/model/RepoConfigurationTest.java
  src/test/java/reposense/parser/AuthorConfigParserTest.java
  src/test/java/reposense/parser/CsvParserTest.java
  src/test/java/reposense/parser/GroupConfigParserTest.java
  src/test/java/reposense/parser/RepoConfigParserTest.java
  src/test/resources/AuthorConfigParserTest/authorconfig_commasAndDoubleQuotes_test.csv
  src/test/resources/AuthorConfigParserTest/authorconfig_emptyLocation_test.csv
  src/test/resources/AuthorConfigParserTest/authorconfig_invalidHeaderSize_test.csv
  src/test/resources/AuthorConfigParserTest/authorconfig_invalidLocation_test.csv
  src/test/resources/AuthorConfigParserTest/authorconfig_multipleEmails_test.csv
  src/test/resources/AuthorConfigParserTest/authorconfig_noSpecialCharacter_test.csv
  src/test/resources/AuthorConfigParserTest/authorconfig_specialCharacter_test.csv
  src/test/resources/AuthorConfigParserTest/require_trailing_whitespaces/authorconfig_emptyConfig_test.csv
  src/test/resources/GroupConfigParserTest/groupconfig_emptyLocation_test.csv
  src/test/resources/GroupConfigParserTest/groupconfig_invalidHeaderSize_test.csv
  src/test/resources/GroupConfigParserTest/groupconfig_invalidLocation_test.csv
  src/test/resources/GroupConfigParserTest/groupconfig_multipleLocation_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_invalidHeaderSize_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_merge_empty_location_test/author-config.csv
  src/test/resources/RepoConfigParserTest/repoconfig_merge_empty_location_test/repo-config.csv
  src/test/resources/RepoConfigParserTest/repoconfig_noSpecialCharacter_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_overrideKeyword_test.csv
  src/test/resources/RepoConfigParserTest/require_trailing_whitespaces/repoconfig_redundantLines_test.csv
Labels: s.ToMerge

#976 [#181] Inconsistent thickness of different contribution bars
  frontend/cypress/tests/contributionBar.js
  frontend/src/index.pug
  frontend/src/static/css/style.scss
Labels: s.ToMerge

#1015 [#1009] Appveyor Failing: remove outdated tests
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
Labels: s.ToReview

#977 [#940] ReportGenerator#generateReposReport: SLAP copying of template file
  src/main/java/reposense/report/ReportGenerator.java
Labels: s.ToMerge

#986 [#960]Refactor Authorship Css
  frontend/src/index.pug
  frontend/src/static/css/style.scss
  frontend/src/static/css/v_authorship.scss
Labels: s.FinalReview

#969 [#879] Display commit tags in commits panel
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_zoom.js
  frontend/src/tabs/zoom.pug
  src/main/java/reposense/commits/CommitInfoAnalyzer.java
  src/main/java/reposense/commits/model/CommitResult.java
  src/main/java/reposense/git/GitLog.java
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Delta_master/commits.json
  src/test/java/reposense/commits/CommitInfoAnalyzerTest.java
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.ToMerge

#895 [#885] Allow reset search filter
  frontend/src/index.pug
  frontend/src/static/css/style.scss
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#1011 [#1001] CSS: Increase z-index for center divider div
  frontend/src/static/css/_colors.scss
  frontend/src/static/css/_utils.scss
  frontend/src/static/css/_z-indices.scss
  frontend/src/static/css/style.scss
Labels: s.ToMerge

#998 [#984] Fix miscalculation of expanded commit message count
  frontend/src/static/js/v_zoom.js
  frontend/src/tabs/zoom.pug
Labels: s.ToMerge

#991 [#988] Ramp chart: inconsistency in the length of contribution line
  src/main/java/reposense/model/FileType.java
Labels: s.ToMerge

#1003 [#960]Refactor Summary CSS
  frontend/src/index.pug
  frontend/src/static/css/style.scss
  frontend/src/static/css/v_summary.scss
Labels: s.ToReview
