Repository reposense/RepoSense, pull requests merged in 2021-04, with the labels that each got.

#1474 [#1472] DG: add release guide
  docs/dg/projectManagement.md
Labels: s.ToMerge

#1466 [#1464] Remove group highlight when merging group
  frontend/src/static/js/v_summary_charts.js
  frontend/src/summary_charts.pug
Labels: s.ToMerge

#1522 [#1517] Restore binary repository in deployment preview
  config/repo-config.csv
Labels: s.ToMerge

#1518 [#1184] Test: improve assertion of authors for file analysis
  src/test/java/reposense/authorship/AnnotatorAnalyzerTest.java
  src/test/java/reposense/authorship/FileAnalyzerTest.java
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.ToMerge

#1487 [#1486] Frontend: rename zIsMerge to zIsMerged
  frontend/src/static/js/main.js
  frontend/src/static/js/v_ramp.js
  frontend/src/static/js/v_summary.js
  frontend/src/static/js/v_zoom.js
Labels: s.FinalReview

#1492 DG: add link to first timer issues
  docs/dg/index.md
Labels: s.ToMerge

#1467 [#1397, #1460] Charts panel: header info misplaced
  frontend/src/static/css/v_summary.scss
Labels: s.ToMerge

#1535 [#634] Extract time-based functionalities to TimeUtil
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/parser/DateArgumentType.java
  src/main/java/reposense/parser/PeriodArgumentType.java
  src/main/java/reposense/parser/SinceDateArgumentType.java
  src/main/java/reposense/parser/UntilDateArgumentType.java
  src/main/java/reposense/util/TimeUtil.java
  src/test/java/reposense/util/TestUtil.java
  src/test/java/reposense/util/TimeUtilTest.java
Labels: s.ToMerge

#1443 Cypress: add test for tabs rendering
  frontend/cypress/tests/codeView/codeView_reload.js
  frontend/cypress/tests/codeView/codeView_switchAuthorship.js
  frontend/cypress/tests/zoomView/zoomView_reload.js
  frontend/cypress/tests/zoomView/zoomView_switchZoom.js
Labels: s.FinalReview

#1480 [#1476] Remove the highlighting when the panel is closed
  frontend/src/static/js/main.js
  frontend/src/static/js/store.js
  frontend/src/static/js/v_summary_charts.js
Labels: s.ToMerge

#1516 [#1515] UG: update documentation on using RepoSense at a specific commit
  docs/ug/runSh.md
Labels: s.ToReview

#1541 Add link to path glob syntax in the User Guide
  docs/ug/configFiles.md
Labels: s.ToReview

#1475 [#1473] Checkbox not working properly in break down by file type
  frontend/src/static/js/v_summary.js
Labels: s.FinalReview

#1521 [#1116] Code Panel: weird syntax highlighting
  frontend/src/index.pug
Labels: s.FinalReview

#1534 [#634] Move logic for getting ReportConfiguration to ArgsParser
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/model/ConfigCliArguments.java
  src/main/java/reposense/parser/ArgsParser.java
Labels: s.ToReview

#1523 UG: reflect new method of CSV parsing
  docs/ug/configFiles.md
Labels: s.ToMerge

#1529 Upgrade cypress version to ^7.0.1
  frontend/cypress/package-lock.json
  frontend/cypress/package.json
  frontend/cypress/tests/chartView/chartView_contributionBar.js
  frontend/cypress/tests/zoomView/zoomView_selectFileTypes.js
Labels: a-Testing, s.ToReview

#1524 Add warning when there are a large number of files to be analyzed
  src/main/java/reposense/authorship/AuthorshipReporter.java
  src/main/java/reposense/authorship/model/FileInfo.java
Labels: s.ToMerge
