Repository reposense/RepoSense, pull requests merged in 2021-08, with the labels that each got.

#1567 Test: remove redundant throws Exception clauses
  src/test/java/reposense/git/GitCloneTest.java
  src/test/java/reposense/util/TimeUtilTest.java
Labels: s.ToMerge

#1569 Fix missing space and use of raw types
  src/main/java/reposense/git/GitCatFile.java
  src/main/java/reposense/parser/CsvParser.java
  src/main/java/reposense/system/CommandRunnerProcess.java
  src/test/java/reposense/git/GitUtilTest.java
  src/test/java/reposense/parser/AuthorConfigParserTest.java
Labels: s.ToMerge

#1566 [#937] Make all tests throw generic Exception
  src/systemtest/java/reposense/ConfigSystemTest.java
  src/test/java/reposense/git/GitLsTreeTest.java
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/util/TestUtil.java
Labels: s.ToMerge

#1574 [#1575] Fix misidentification of deleted files as edited files
  src/main/java/reposense/authorship/FileInfoExtractor.java
Labels: s.ToMerge

#1412 [#795] Projectify frontend part
  .eslintrc.json
  .github/workflows/integration.yml
  .gitignore
  build.gradle
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.pug-lintrc.json
  frontend/.stylelintrc.json
  frontend/babel.config.js
  frontend/cypress/.eslintrc.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/app.vue
  frontend/src/components/v-ramp.vue
  frontend/src/components/v-resizer.vue
  frontend/src/components/v-segment.vue
  frontend/src/components/v-summary-charts.vue
  frontend/src/index.pug
  frontend/src/main.js
  frontend/src/ramp.pug
  frontend/src/resizer.pug
  frontend/src/static/css/v_authorship.scss
  frontend/src/static/css/v_ramp.scss
  frontend/src/static/css/v_summary.scss
  frontend/src/static/css/v_zoom.scss
  frontend/src/static/js/v_segment.js
  frontend/src/static/js/v_zoom.js
  frontend/src/store/store.js
  frontend/src/styles/_colors.scss
  frontend/src/styles/_utils.scss
  frontend/src/styles/_z-indices.scss
  frontend/src/styles/panels.scss
  frontend/src/styles/style.scss
  frontend/src/summary.pug
  frontend/src/summary_charts.pug
  frontend/src/tabs/authorship.pug
  frontend/src/tabs/zoom.pug
  frontend/src/utils/api.js
  frontend/src/utils/load-font-awesome-icons.js
  frontend/src/utils/ramp-colour-generator.js
  frontend/src/utils/repo-sorter.js
  frontend/src/utils/safari_date.js
  frontend/src/views/v-authorship.vue
  frontend/src/views/v-summary.vue
  frontend/src/views/v-zoom.vue
  frontend/vue.config.js
  package.json
Labels: s.ToReview

#1580 Cypress: replace nonexistent input element with pug id in selector in codeView_reload.js
  frontend/cypress/tests/codeView/codeView_reload.js
Labels: s.ToReview

#1585 Include the frontend gradle hot reload feature in DG
  docs/dg/workflow.md
  frontend/.gitignore
Labels: a-Docs

#1577 [#1463] Fix case insensitive bug in @@author feature
  src/main/java/reposense/model/AuthorConfiguration.java
Labels: s.ToMerge

#1562 [#1546] RepoCloner: fix local repos relative pathing and spaces
  src/main/java/reposense/git/GitClone.java
  src/main/java/reposense/model/RepoLocation.java
  src/main/java/reposense/report/RepoCloner.java
  src/main/java/reposense/system/CommandRunnerProcess.java
  src/main/java/reposense/util/StringsUtil.java
  src/test/java/reposense/git/GitLsTreeTest.java
  src/test/java/reposense/report/RepoClonerTest.java
  src/test/java/reposense/util/StringsUtilTest.java
Labels: s.ToMerge

#1554 [#382, #1568] Make annotation tagged author appear in report
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/authorship/FileInfoAnalyzer.java
  src/main/java/reposense/authorship/analyzer/AnnotatorAnalyzer.java
  src/main/java/reposense/model/AuthorConfiguration.java
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/report/ReportGenerator.java
  src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Beta_master/authorship.json
  src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Charlie_master/authorship.json
  src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Beta_master/authorship.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Delta_master/authorship.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Delta_master/commits.json
  src/test/java/reposense/authorship/AnnotatorAnalyzerTest.java
  src/test/java/reposense/commits/CommitInfoAnalyzerTest.java
  src/test/java/reposense/git/GitLogTest.java
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.ToMerge

#1578 [#1547] Style: change if statements to use ternary operator
  docs/dg/styleGuides.md
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/main/java/reposense/authorship/analyzer/AnnotatorAnalyzer.java
  src/main/java/reposense/commits/CommitResultAggregator.java
  src/main/java/reposense/model/ReportConfiguration.java
  src/main/java/reposense/model/StandaloneAuthor.java
  src/main/java/reposense/parser/CsvParser.java
  src/main/java/reposense/report/RepoCloner.java
  src/main/java/reposense/util/StringsUtil.java
Labels: s.ToMerge

#1581 [#1536] Frontend: show short commit hash in commits view
  frontend/src/styles/panels.scss
  frontend/src/views/v-zoom.vue
Labels: s.ToMerge

#1582 [#1510] Frontend: implement resetting of file type checkboxes
  frontend/src/views/v-summary.vue
Labels: s.ToMerge

#1576 [#1571] Fix incorrect invalidation of file path with spaces
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
  src/test/java/reposense/commits/CommitInfoAnalyzerTest.java
  src/test/java/reposense/git/GitShortlogTest.java
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.ToMerge

#1559 [#1557] Migrate docs to use MarkBind V3
  .github/workflows/gh-pages.yml
  .github/workflows/integration.yml
  docs/_markbind/headers/devSiteHeader.md
  docs/_markbind/layouts/body.md
  docs/_markbind/layouts/default.md
  docs/_markbind/layouts/default/footer.md
  docs/_markbind/layouts/default/head.md
  docs/_markbind/layouts/default/page.md
  docs/_markbind/layouts/default/scripts.js
  docs/_markbind/layouts/default/styles.css
  docs/_markbind/layouts/dg-layout.md
  docs/_markbind/layouts/dg-sitenav.md
  docs/_markbind/layouts/dg-topnav.md
  docs/_markbind/layouts/footer.md
  docs/_markbind/layouts/head.md
  docs/_markbind/layouts/topnav.md
  docs/_markbind/layouts/ug-layout.md
  docs/_markbind/layouts/ug-sitenav.md
  docs/_markbind/layouts/ug-topnav.md
  docs/about.md
  docs/contact.md
  docs/css/main.css
  docs/dg/architecture.md
  docs/dg/devOpsGuide.md
  docs/dg/index.md
  docs/dg/learningBasics.md
  docs/dg/projectManagement.md
  docs/dg/report.md
  docs/dg/settingUp.md
  docs/dg/styleGuides.md
  docs/dg/workflow.md
  docs/index.md
  docs/scripts/macros.njk
  docs/showcase.md
  docs/site.json
  docs/ug/cli.md
  docs/ug/configFiles.md
  docs/ug/customizingReports.md
  docs/ug/faq.md
  docs/ug/generatingReports.md
  docs/ug/index.md
  docs/ug/runSh.md
  docs/ug/sharingReports.md
  docs/ug/troubleshooting.md
  docs/ug/usingAuthorTags.md
  docs/ug/usingReports.md
  docs/ug/withGithubActions.md
  docs/ug/withNetlify.md
  docs/ug/withTravis.md
Labels: s.ToMerge

#1561 ConfigParser: fix Ignore Commits List header typo in CSV files
  .gitignore
  _reposense/config.json
  docs/ug/configFiles.md
  src/main/java/reposense/model/StandaloneConfig.java
  src/main/java/reposense/parser/RepoConfigCsvParser.java
  src/systemtest/resources/repo-config.csv
  src/test/java/reposense/git/GitShortlogTest.java
  src/test/java/reposense/template/GitTestTemplate.java
  src/test/resources/CsvParserTest/repoconfig_zeroValidRecords_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_differentColumnOrder_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_duplicateHeadersCaseInsensitive_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_duplicateHeadersCaseSensitive_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_merge_empty_location_test/repo-config.csv
  src/test/resources/RepoConfigParserTest/repoconfig_missingMandatoryHeader_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_noSpecialCharacter_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_overrideKeyword_test.csv
  src/test/resources/RepoConfigParserTest/require_trailing_whitespaces/repoconfig_redundantLines_test.csv
  src/test/resources/RepoConfigurationTest/repoconfig_formats_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_groups_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_ignoreAuthors_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_ignoreStandAloneKeyword_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_ignoreStandAlone_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_ignoreStandaloneOverrideCsv_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_overrideStandAlone_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_shallowCloningOverrideCsv_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_shallowCloning_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_withoutformats_test/repo-config.csv
  src/test/resources/StandaloneConfigJsonParserTest/standaloneConfig_full.json
  src/test/resources/StandaloneConfigTest/authors_trailingCommas_config.json
  src/test/resources/StandaloneConfigTest/invalidIgnoreCommit_config.json
  src/test/resources/StandaloneConfigTest/lithiumlkid_invalidIgnoreGlob_config.json
  src/test/resources/StandaloneConfigTest/lithiumlkid_trailingCommas_config.json
  src/test/resources/StandaloneConfigTest/specialCharacterAuthor_config.json
  src/test/resources/StandaloneConfigTest/valid_config.json
  src/test/resources/cli_location_test/repo-config.csv
  src/test/resources/repoconfig_empty_branch_test/repo-config.csv
  src/test/resources/repoconfig_merge_test/repo-config.csv
Labels: s.ToMerge
