Repository reposense/RepoSense, pull requests merged in 2021-03, with the labels that each got.

#1419 Rewrite how zoom refreshes
  frontend/src/static/js/main.js
  frontend/src/static/js/v_summary.js
  frontend/src/static/js/v_zoom.js
Labels: s.ToReview

#1453 [#1352] Add highlight to selected authorship or commit tab
  frontend/src/static/css/v_summary.scss
  frontend/src/static/js/v_summary_charts.js
  frontend/src/summary_charts.pug
Labels: s.ToMerge

#1457 v_summary_charts: fix typo of some arguments
  frontend/src/static/js/v_summary_charts.js
  frontend/src/tabs/zoom.pug
Labels: s.ToMerge

#1458 [#1446] Restore the name on authorship panel after reloading
  frontend/src/static/js/v_authorship.js
  frontend/src/tabs/authorship.pug
Labels: s.FinalReview

#1413 [#674] Include binary files touched in authorship panel
  config/repo-config.csv
  docs/ug/cli.md
  docs/ug/configFiles.md
  docs/ug/troubleshooting.md
  docs/ug/usingReports.md
  frontend/src/static/css/panels.scss
  frontend/src/static/css/v_authorship.scss
  frontend/src/static/js/v_authorship.js
  frontend/src/tabs/authorship.pug
  src/main/java/reposense/authorship/AuthorshipReporter.java
  src/main/java/reposense/authorship/FileInfoAnalyzer.java
  src/main/java/reposense/authorship/FileInfoExtractor.java
  src/main/java/reposense/authorship/FileResultAggregator.java
  src/main/java/reposense/authorship/model/FileResult.java
  src/main/java/reposense/git/GitLog.java
  src/test/java/reposense/authorship/AnnotatorAnalyzerTest.java
  src/test/java/reposense/authorship/FileAnalyzerTest.java
  src/test/java/reposense/authorship/FileInfoExtractorTest.java
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.ToMerge

#1482 Frontend: remove browsersify and vueify
  build.gradle
  frontend/src/index.pug
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_zoom.js
  package.json
Labels: s.ToMerge

#1490 [#1485] Watch tab info directly
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_zoom.js
Labels: s.ToMerge

#1459 CSVParser: check column headers when parsing config CSV files
  config/author-config.csv
  config/group-config.csv
  src/main/java/reposense/parser/AuthorConfigCsvParser.java
  src/main/java/reposense/parser/CsvParser.java
  src/main/java/reposense/parser/GroupConfigCsvParser.java
  src/main/java/reposense/parser/RepoConfigCsvParser.java
  src/systemtest/resources/author-config.csv
  src/systemtest/resources/group-config.csv
  src/systemtest/resources/repo-config.csv
  src/test/java/reposense/parser/AuthorConfigParserTest.java
  src/test/java/reposense/parser/GroupConfigParserTest.java
  src/test/java/reposense/parser/RepoConfigParserTest.java
  src/test/resources/AuthorConfigParserTest/authorconfig_commasAndDoubleQuotes_test.csv
  src/test/resources/AuthorConfigParserTest/authorconfig_differentColumnOrder_test.csv
  src/test/resources/AuthorConfigParserTest/authorconfig_emptyLocation_test.csv
  src/test/resources/AuthorConfigParserTest/authorconfig_invalidHeaderSize_test.csv
  src/test/resources/AuthorConfigParserTest/authorconfig_invalidLocation_test.csv
  src/test/resources/AuthorConfigParserTest/authorconfig_missingMandatoryHeader_test.csv
  src/test/resources/AuthorConfigParserTest/authorconfig_missingOptionalHeader_test.csv
  src/test/resources/AuthorConfigParserTest/authorconfig_multipleEmails_test.csv
  src/test/resources/AuthorConfigParserTest/authorconfig_noSpecialCharacter_test.csv
  src/test/resources/AuthorConfigParserTest/authorconfig_specialCharacter_test.csv
  src/test/resources/CsvParserTest/repoconfig_zeroValidRecords_test.csv
  src/test/resources/GroupConfigParserTest/groupconfig_differentColumnOrder_test.csv
  src/test/resources/GroupConfigParserTest/groupconfig_emptyLocation_test.csv
  src/test/resources/GroupConfigParserTest/groupconfig_invalidHeaderSize_test.csv
  src/test/resources/GroupConfigParserTest/groupconfig_invalidLocation_test.csv
  src/test/resources/GroupConfigParserTest/groupconfig_missingMandatoryHeader_test.csv
  src/test/resources/GroupConfigParserTest/groupconfig_missingOptionalHeader_test.csv
  src/test/resources/GroupConfigParserTest/groupconfig_multipleLocation_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_differentColumnOrder_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_duplicateHeadersCaseInsensitive_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_duplicateHeadersCaseSensitive_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_invalidHeaderSize_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_merge_empty_location_test/author-config.csv
  src/test/resources/RepoConfigParserTest/repoconfig_merge_empty_location_test/repo-config.csv
  src/test/resources/RepoConfigParserTest/repoconfig_missingMandatoryHeader_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_missingOptionalHeader_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_noSpecialCharacter_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_overrideKeyword_test.csv
  src/test/resources/RepoConfigParserTest/require_trailing_whitespaces/repoconfig_redundantLines_test.csv
  src/test/resources/RepoConfigurationTest/repoconfig_formats_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_groups_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_ignoreAuthors_test/author-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_ignoreAuthors_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_ignoreStandAloneKeyword_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_ignoreStandAlone_test/author-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_ignoreStandAlone_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_ignoreStandaloneOverrideCsv_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_overrideStandAlone_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_shallowCloningOverrideCsv_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_shallowCloning_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_withoutformats_test/repo-config.csv
  src/test/resources/cli_location_test/author-config.csv
  src/test/resources/cli_location_test/repo-config.csv
  src/test/resources/repoconfig_empty_branch_test/author-config.csv
  src/test/resources/repoconfig_empty_branch_test/repo-config.csv
  src/test/resources/repoconfig_merge_test/author-config.csv
  src/test/resources/repoconfig_merge_test/repo-config.csv
Labels: s.FinalReview

#1461 [#1229] Select a consistent group name when grouped by author
  frontend/src/static/js/api.js
  frontend/src/static/js/utils/repo_sorter.js
  frontend/src/static/js/v_summary_charts.js
  frontend/src/summary_charts.pug
Labels: s.FinalReview

#1465 [#1448] Update documentation to remove need for personal access token
  docs/images/publishingguide-secrets.png
  docs/ug/withGithubActions.md
  docs/ug/withTravis.md
Labels: s.FinalReview

#1451 [#1452] Implement multi-threading
  docs/dg/architecture.md
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/model/CliArguments.java
  src/main/java/reposense/model/ConfigCliArguments.java
  src/main/java/reposense/model/LocationsCliArguments.java
  src/main/java/reposense/parser/AnalysisThreadsArgumentType.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/parser/CloningThreadsArgumentType.java
  src/main/java/reposense/report/AnalysisErrorInfo.java
  src/main/java/reposense/report/AnalyzeJobOutput.java
  src/main/java/reposense/report/CloneJobOutput.java
  src/main/java/reposense/report/RepoCloner.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/util/FileUtil.java
  src/systemtest/java/reposense/ConfigSystemTest.java
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/util/InputBuilder.java
Labels: s.FinalReview, s.ToMerge
