Repository reposense/RepoSense, pull requests merged in 2021-05, with the labels that each got.

#1503 [#1435] Expand continuous integration testing to Ubuntu 18.04 and 20.04
  .github/workflows/integration.yml
Labels: s.ToMerge

#1513 [#1512] Seemingly random disappearance of dates
  frontend/src/index.pug
  frontend/src/static/js/main.js
  frontend/src/static/js/v_summary.js
Labels: s.ToMerge

#1509 [#1190] Add message for invalid repository link on the summary view
  config/repo-config.csv
  src/main/java/reposense/model/RepoLocation.java
  src/test/java/reposense/model/RepoConfigurationTest.java
  src/test/java/reposense/parser/RepoConfigParserTest.java
  src/test/resources/AuthorConfigParserTest/authorconfig_invalidLocation_test.csv
  src/test/resources/GroupConfigParserTest/groupconfig_invalidLocation_test.csv
  src/test/resources/RepoConfigParserTest/repoconfig_invalidLocation_test.csv
Labels: s.ToReview

#1507 [#1500] Add a Learn basics section to the DG
  docs/_markbind/navigation/dgSiteNav.md
  docs/dg/index.md
  docs/dg/learningBasics.md
  docs/dg/workflow.md
Labels: s.ToReview

#1520 [#1354] Allow disowning of code by using empty author tags
  docs/ug/usingAuthorTags.md
  src/main/java/reposense/authorship/analyzer/AnnotatorAnalyzer.java
  src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Charlie_master/authorship.json
  src/systemtest/resources/30daysFromUntilDate/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Charlie_master/authorship.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Delta_master/authorship.json
  src/systemtest/resources/sinceBeginningDateRange/expected/reposense_testrepo-Delta_master/commits.json
  src/test/java/reposense/authorship/AnnotatorAnalyzerTest.java
  src/test/java/reposense/commits/CommitInfoAnalyzerTest.java
  src/test/java/reposense/git/GitLogTest.java
  src/test/java/reposense/git/GitShortlogTest.java
  src/test/java/reposense/template/GitTestTemplate.java
Labels: s.Ongoing
