Repository reposense/RepoSense, pull requests merged in 2021-02, with the labels that each got.

#1416 [#1340] v_segment: rewrite toggling logic
  frontend/src/static/css/v_authorship.scss
  frontend/src/static/js/v_segment.js
  frontend/src/tabs/segment.pug
Labels: s.ToMerge

#1389 Documentation: fix grammatical mistakes
  docs/about.md
  docs/dg/architecture.md
  docs/dg/index.md
  docs/dg/projectManagement.md
  docs/dg/report.md
  docs/index.md
  docs/showcase.md
  docs/ug/configFiles.md
  docs/ug/faq.md
  docs/ug/generatingReports.md
  docs/ug/sharingReports.md
  docs/ug/troubleshooting.md
  docs/ug/usingAuthorTags.md
  docs/ug/usingReports.md
Labels: s.ToMerge

#1408 [#1407] DG: add Gradle instructions to workflow
  docs/dg/workflow.md
Labels: a-Docs, s.ToMerge

#1422 DG: remove need to open PR for small issues
  docs/dg/workflow.md
Labels: s.ToMerge

#1442 [#1423] Fix Vue build warning
  .eslintrc.json
  frontend/src/static/js/safari_date.js
Labels: s.ToMerge

#1418 [#1417] Change the way api.js loads json files
  frontend/src/static/js/api.js
  frontend/src/static/js/main.js
Labels: s.ToMerge

#1405 [#1404] DG: edit the running from code part
  docs/dg/workflow.md
Labels: a-Docs, s.ToMerge

#1437 [#1426] Zoom reloading not function properly
  frontend/src/tabs/zoom.pug
Labels: s.FinalReview

#1406 [#1401] Replace images as puml diagrams
  docs/dg/report.md
  docs/diagrams/ReportArchitecture.puml
  docs/diagrams/ReportArchitectureAuthorship.puml
  docs/diagrams/ReportArchitectureSummary.puml
  docs/images/report-architecture-authorship.png
  docs/images/report-architecture-summary.png
  docs/images/report-architecture.png
Labels: a-Docs, s.ToReview

#1390 [#1382] Avoid rerendering tabs unnecessarily
  frontend/src/index.pug
  frontend/src/static/js/main.js
  frontend/src/static/js/v_authorship.js
  frontend/src/static/js/v_zoom.js
Labels: s.ToMerge
