Repository reposense/RepoSense, pull requests merged in 2025-04, with the labels that each got.

#2329 [#2200] Refactor c-title to use c-markdown-chunk
  frontend/src/components/c-title.vue
Labels: c.Enhancement, s.ToMerge

#2325 [#2326] Optimize Vite Chunk Size
  frontend/package-lock.json
  frontend/package.json
  frontend/vite.config.mts
Labels: s.ToMerge

#2337 [#2332] Frontend Sort Function Bugfix and Enhancement
  frontend/cypress/tests/chartView/chartView_showTags.cy.js
  frontend/src/types/window.ts
  frontend/src/utils/api.ts
  frontend/src/utils/repo-sorter.ts
  frontend/src/views/c-summary.vue
Labels: c.Bug, c.Enhancement, s.ToMerge

#2369 [#2366] Support datetime for since and until CLI config
  .gitignore
  docs/ug/cli.md
  frontend/cypress/tests/chartView/chartView_mergeCommits.cy.js
  frontend/cypress/tests/chartView/chartView_optimiseTimeline.cy.js
  frontend/cypress/tests/chartView/chartView_reload.cy.js
  frontend/cypress/tests/chartView/chartView_zoomFeature.cy.js
  frontend/cypress/tests/codeView/codeView_renderFilterHash.cy.js
  frontend/cypress/tests/portfolioView/portfolioView_optimiseTimeline.cy.js
  frontend/cypress/tests/zoomView/zoomView_rampChart.cy.js
  frontend/src/components/c-summary-header.vue
  frontend/src/views/c-summary.vue
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/parser/types/DateArgumentType.java
  src/main/java/reposense/parser/types/SinceDateArgumentType.java
  src/main/java/reposense/parser/types/UntilDateArgumentType.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/util/TimeUtil.java
  src/main/java/reposense/util/adapters/DateSerializer.java
  src/systemtest/java/reposense/ConfigSystemTest.java
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDate/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDate/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDate/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateFindPreviousAuthors/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateFindPreviousAuthors/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateFindPreviousAuthors/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateWithShallowCloning/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateWithShallowCloning/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateWithShallowCloning/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/dateRangeWithModifiedDateTimeInLines/expected/reposense_testrepo-Beta_master/authorship.json
  src/systemtest/resources/ConfigSystemTest/dateRangeWithModifiedDateTimeInLines/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/dateRangeWithModifiedDateTimeInLines/expected/reposense_testrepo-Charlie_master/authorship.json
  src/systemtest/resources/ConfigSystemTest/dateRangeWithModifiedDateTimeInLines/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRange/expected/reposense_testrepo-Alpha_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRange/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRange/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRange/expected/reposense_testrepo-Delta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRange/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeFindPreviousAuthors/expected/reposense_testrepo-Alpha_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeFindPreviousAuthors/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeFindPreviousAuthors/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeFindPreviousAuthors/expected/reposense_testrepo-Delta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeFindPreviousAuthors/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithPortfolio/expected/reposense_testrepo-Alpha_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithPortfolio/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithPortfolio/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithPortfolio/expected/reposense_testrepo-Delta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithPortfolio/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithShallowCloning/expected/reposense_testrepo-Alpha_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithShallowCloning/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithShallowCloning/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithShallowCloning/expected/reposense_testrepo-Delta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithShallowCloning/expected/summary.json
  src/systemtest/resources/LocalRepoSystemTest/testRelativePathing/parent1_test-repo_master/commits.json
  src/systemtest/resources/LocalRepoSystemTest/testRelativePathing/summary.json
  src/systemtest/resources/LocalRepoSystemTest/testSameFinalDirectory/parent1_test-repo_master/commits.json
  src/systemtest/resources/LocalRepoSystemTest/testSameFinalDirectory/parent2_test-repo_master/commits.json
  src/systemtest/resources/LocalRepoSystemTest/testSameFinalDirectory/summary.json
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/util/TimeUtilTest.java
Labels: p.High, s.ToMerge, a-Backend, a-FrontEnd

#2343 [#2100] Add RepoSense attribution to widget
  .gitignore
  frontend/cypress/tests/chartView/chartView_widget.cy.js
  frontend/package.json
  frontend/public/logo.png
  frontend/src/types/window.ts
  frontend/src/utils/api.ts
  frontend/src/views/c-summary.vue
Labels: c.Feature, s.ToMerge

#2388 [#2366] Support datetime since until
  docs/ug/cli.md
  frontend/cypress/tests/chartView/chartView_mergeCommits.cy.js
  frontend/cypress/tests/chartView/chartView_optimiseTimeline.cy.js
  frontend/cypress/tests/chartView/chartView_reload.cy.js
  frontend/cypress/tests/chartView/chartView_zoomFeature.cy.js
  frontend/cypress/tests/codeView/codeView_renderFilterHash.cy.js
  frontend/cypress/tests/portfolioView/portfolioView_optimiseTimeline.cy.js
  frontend/cypress/tests/zoomView/zoomView_rampChart.cy.js
  frontend/src/components/c-ramp.vue
  frontend/src/components/c-summary-header.vue
  frontend/src/views/c-summary.vue
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/parser/types/DateArgumentType.java
  src/main/java/reposense/parser/types/SinceDateArgumentType.java
  src/main/java/reposense/parser/types/UntilDateArgumentType.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/util/TimeUtil.java
  src/main/java/reposense/util/adapters/DateSerializer.java
  src/systemtest/java/reposense/ConfigSystemTest.java
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDate/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDate/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDate/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateFindPreviousAuthors/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateFindPreviousAuthors/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateFindPreviousAuthors/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateWithShallowCloning/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateWithShallowCloning/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateWithShallowCloning/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/dateRangeWithModifiedDateTimeInLines/expected/reposense_testrepo-Beta_master/authorship.json
  src/systemtest/resources/ConfigSystemTest/dateRangeWithModifiedDateTimeInLines/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/dateRangeWithModifiedDateTimeInLines/expected/reposense_testrepo-Charlie_master/authorship.json
  src/systemtest/resources/ConfigSystemTest/dateRangeWithModifiedDateTimeInLines/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRange/expected/reposense_testrepo-Alpha_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRange/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRange/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRange/expected/reposense_testrepo-Delta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRange/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeFindPreviousAuthors/expected/reposense_testrepo-Alpha_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeFindPreviousAuthors/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeFindPreviousAuthors/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeFindPreviousAuthors/expected/reposense_testrepo-Delta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeFindPreviousAuthors/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithPortfolio/expected/reposense_testrepo-Alpha_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithPortfolio/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithPortfolio/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithPortfolio/expected/reposense_testrepo-Delta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithPortfolio/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithShallowCloning/expected/reposense_testrepo-Alpha_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithShallowCloning/expected/reposense_testrepo-Beta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithShallowCloning/expected/reposense_testrepo-Charlie_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithShallowCloning/expected/reposense_testrepo-Delta_master/commits.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithShallowCloning/expected/summary.json
  src/systemtest/resources/LocalRepoSystemTest/testRelativePathing/parent1_test-repo_master/commits.json
  src/systemtest/resources/LocalRepoSystemTest/testRelativePathing/summary.json
  src/systemtest/resources/LocalRepoSystemTest/testSameFinalDirectory/parent1_test-repo_master/commits.json
  src/systemtest/resources/LocalRepoSystemTest/testSameFinalDirectory/parent2_test-repo_master/commits.json
  src/systemtest/resources/LocalRepoSystemTest/testSameFinalDirectory/summary.json
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/util/TimeUtilTest.java
Labels: s.ToMerge

#2331 [#2210] Add default sort order for groups
  docs/ug/configFiles.md
  docs/ug/usingReports.md
  frontend/cypress/tests/chartView/chartView_sorting.cy.js
  frontend/src/app.vue
  frontend/src/components/c-summary-header.vue
  frontend/src/types/summary.ts
  frontend/src/types/types.ts
  frontend/src/types/window.ts
  frontend/src/utils/api.ts
Labels: c.Feature, s.ToMerge

#2339 [#2311] Add blurbs for Authors
  config/author-blurbs.md
  config/repo-blurbs.md
  docs/ug/author-blurbs.md
  docs/ug/configFiles.md
  docs/ug/repo-blurbs.md
  frontend/cypress/configs/default/author-blurbs.md
  frontend/cypress/configs/default/repo-blurbs.md
  frontend/cypress/configs/portfolio/author-blurbs.md
  frontend/cypress/configs/portfolio/repo-blurbs.md
  frontend/cypress/tests/chartView/chartView_author_blurbs.cy.js
  frontend/src/app.vue
  frontend/src/components/c-summary-charts.vue
  frontend/src/store/store.ts
  frontend/src/types/vuex.d.ts
  frontend/src/types/window.ts
  frontend/src/types/zod/summary-type.ts
  frontend/src/utils/api.ts
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/model/AbstractBlurbMap.java
  src/main/java/reposense/model/AuthorBlurbMap.java
  src/main/java/reposense/model/BlurbMap.java
  src/main/java/reposense/model/CliArguments.java
  src/main/java/reposense/model/RepoBlurbMap.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/parser/AuthorBlurbMarkdownParser.java
  src/main/java/reposense/parser/BlurbMarkdownParser.java
  src/main/java/reposense/parser/RepoBlurbMarkdownParser.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/report/SummaryJson.java
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDate/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateFindPreviousAuthors/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateWithShallowCloning/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/author-blurbs.md
  src/systemtest/resources/ConfigSystemTest/repo-blurbs.md
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRange/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeFindPreviousAuthors/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithPortfolio/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithShallowCloning/expected/summary.json
  src/systemtest/resources/LocalRepoSystemTest/testRelativePathing/summary.json
  src/systemtest/resources/LocalRepoSystemTest/testSameFinalDirectory/summary.json
  src/test/java/reposense/model/AuthorBlurbMapTest.java
  src/test/java/reposense/model/RepoBlurbMapTest.java
  src/test/java/reposense/parser/AuthorBlurbMarkdownParserTest.java
  src/test/java/reposense/parser/RepoBlurbMarkdownParserTest.java
  src/test/resources/BlurbMarkdownParserTest/AuthorBlurbMarkdownParserTest/malformed_delimiter_blurb.md
  src/test/resources/BlurbMarkdownParserTest/AuthorBlurbMarkdownParserTest/multiline_blurb.md
  src/test/resources/BlurbMarkdownParserTest/AuthorBlurbMarkdownParserTest/multiple_blurbs.md
  src/test/resources/BlurbMarkdownParserTest/RepoBlurbMarkdownParserTest/malformed_delimiter_blurb.md
  src/test/resources/BlurbMarkdownParserTest/RepoBlurbMarkdownParserTest/malformed_url_blurb.md
  src/test/resources/BlurbMarkdownParserTest/RepoBlurbMarkdownParserTest/multiline_blurb.md
  src/test/resources/BlurbMarkdownParserTest/RepoBlurbMarkdownParserTest/multiple_blurbs.md
Labels: c.Feature, s.ToMerge, a-Backend, a-FrontEnd

#2338 [#2212] Refresh Only Text
  docs/ug/cli.md
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/model/CliArguments.java
  src/main/java/reposense/model/RepoLocation.java
  src/main/java/reposense/model/ReportConfiguration.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/parser/SummaryJsonParser.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/report/SummaryJson.java
  src/main/java/reposense/util/FileUtil.java
  src/main/java/reposense/util/adapters/DateDeserializer.java
  src/main/java/reposense/util/adapters/ZoneDeserializer.java
  src/test/java/reposense/parser/ArgsParserTest.java
  src/test/java/reposense/parser/SummaryJsonParserTest.java
  src/test/java/reposense/report/ReportGeneratorTest.java
  src/test/java/reposense/report/SummaryJsonTest.java
  src/test/java/reposense/util/FileUtilTest.java
  src/test/java/reposense/util/InputBuilder.java
  src/test/resources/FileUtilTest/expectedReplacedSummaryJson/reposense_testrepo-Beta/authorship.json
  src/test/resources/FileUtilTest/expectedReplacedSummaryJson/reposense_testrepo-Beta/commits.json
  src/test/resources/FileUtilTest/expectedReplacedSummaryJson/reposense_testrepo-Charlie/authorship.json
  src/test/resources/FileUtilTest/expectedReplacedSummaryJson/reposense_testrepo-Charlie/commits.json
  src/test/resources/FileUtilTest/expectedReplacedSummaryJson/summary.json
  src/test/resources/FileUtilTest/summary.json
  src/test/resources/ReportGeneratorTest/original_files/summary.json
  src/test/resources/ReportGeneratorTest/original_files/title.md
  src/test/resources/ReportGeneratorTest/summary.json
  src/test/resources/ReportGeneratorTest/test_assets/title.md
  src/test/resources/ReportGeneratorTest/title.md
  src/test/resources/SummaryJsonParserTest/empty-summary.json
  src/test/resources/SummaryJsonParserTest/invalid-summary.json
  src/test/resources/SummaryJsonParserTest/valid-summary.json
Labels: s.ToMerge, a-Backend

#2322 [#2106] Implement comparison of files across repos
  docs/ug/cli.md
  docs/ug/usingReports.md
  frontend/cypress/tests/chartView/chartView_reload.cy.js
  frontend/cypress/tests/chartView/chartView_toolBar_searchBox.cy.js
  frontend/cypress/tests/codeView/codeView_renderFilterHash.cy.js
  frontend/cypress/tests/portfolioView/portfolioView_header.cy.js
  frontend/src/components/c-summary-header.vue
  frontend/src/mixin/dynamicTooltipMixin.ts
  frontend/src/store/store.ts
  frontend/src/styles/summary-chart.scss
  frontend/src/views/c-authorship.vue
  frontend/src/views/c-home.vue
  frontend/src/views/c-summary.vue
Labels: s.ToMerge, a-FrontEnd

#2394 [#2391][#2992] Update User Guide and Clean Up Code
  docs/ug/configFiles.md
  docs/ug/customizingReports.md
  src/main/java/reposense/parser/RepoBlurbMarkdownParser.java
Labels: s.ToMerge

#2409 [#2400] Fix Java 17 Compilation Error
  src/main/java/reposense/util/FileUtil.java
Labels: s.ToMerge

#2410 [#2399] Fix BE tests
  src/test/java/reposense/report/ReportGeneratorTest.java
Labels: s.ToMerge

#2315 [#2205] Move title.md to config directory
  codecov.yml
  config/assets/favicon.ico
  docs/ug/customizingReports.md
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/model/CliArguments.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/parser/types/AssetsFolderArgumentType.java
  src/main/java/reposense/report/ReportGenerator.java
  src/test/java/reposense/model/RepoConfigurationTest.java
  src/test/java/reposense/util/AssertUtil.java
Labels: s.ToMerge, a-Backend

#2340 [#2334] Resolve conflict between CLI and CSV dates
  docs/ug/configFiles.md
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/model/ConfigRunConfiguration.java
  src/main/java/reposense/model/RepoConfiguration.java
  src/main/java/reposense/model/RunConfiguration.java
  src/main/java/reposense/parser/CsvParser.java
  src/main/java/reposense/parser/RepoConfigCsvParser.java
  src/main/java/reposense/parser/exceptions/InvalidDatesException.java
  src/main/java/reposense/report/ReportGenerator.java
  src/test/java/reposense/model/RepoConfigurationTest.java
  src/test/java/reposense/parser/RepoConfigParserTest.java
  src/test/resources/CsvParserTest/repocsvconfig_invalidCsvDate_test.csv
  src/test/resources/CsvParserTest/repocsvconfig_mixedValidityCsvDate_test.csv
  src/test/resources/RepoConfigurationTest/repoconfig_nonportfolio_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_testCsvNoCliDates_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_testCsvWithCliDates_test/repo-config.csv
  src/test/resources/RepoConfigurationTest/repoconfig_withoutformats_test/repoconfig_testCsvNoCliDates_test/repo-config.csv
Labels: s.ToMerge, a-Backend

#2428 [#2426] Fix bugs in UG for blurbs
  docs/ug/configFiles.md
Labels: c.Bug, a-Docs, s.ToMerge, p.Urgent

#2414 [#2359] Refactor summary components
  frontend/src/components/c-error-message-box.vue
  frontend/src/components/c-ramp.vue
  frontend/src/components/c-summary-charts.vue
  frontend/src/components/c-summary-header.vue
  frontend/src/components/c-zoom-commit-message.vue
  frontend/src/mixin/summaryMixin.ts
  frontend/src/views/c-summary-portfolio.vue
  frontend/src/views/c-summary.vue
Labels: s.ToMerge

#2350 [#2308] Add blurbs for charts
  config/chart-blurbs.md
  docs/ug/chart-blurbs.md
  docs/ug/configFiles.md
  docs/ug/customizingReports.md
  docs/ug/reportConfig.md
  src/main/java/reposense/RepoSense.java
  src/main/java/reposense/model/ChartBlurbMap.java
  src/main/java/reposense/model/CliArguments.java
  src/main/java/reposense/parser/ArgsParser.java
  src/main/java/reposense/parser/ChartBlurbMarkdownParser.java
  src/main/java/reposense/report/ReportGenerator.java
  src/main/java/reposense/report/SummaryJson.java
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDate/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateFindPreviousAuthors/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/30daysFromUntilDateWithShallowCloning/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/chart-blurbs.md
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRange/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeFindPreviousAuthors/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithPortfolio/expected/summary.json
  src/systemtest/resources/ConfigSystemTest/sinceBeginningDateRangeWithShallowCloning/expected/summary.json
  src/systemtest/resources/LocalRepoSystemTest/testRelativePathing/summary.json
  src/systemtest/resources/LocalRepoSystemTest/testSameFinalDirectory/summary.json
  src/systemtest/resources/ReportConfigSystemTest/30daysFromUntilDate/expected/summary.json
  src/systemtest/resources/ReportConfigSystemTest/30daysFromUntilDateWithShallowCloning/expected/summary.json
  src/systemtest/resources/ReportConfigSystemTest/dateRangeWithModifiedDateTimeInLines/expected/summary.json
  src/systemtest/resources/ReportConfigSystemTest/sinceBeginningDateRange/expected/summary.json
  src/systemtest/resources/ReportConfigSystemTest/sinceBeginningDateRangeWithPortfolio/expected/summary.json
  src/systemtest/resources/ReportConfigSystemTest/sinceBeginningDateRangeWithShallowCloning/expected/summary.json
  src/test/java/reposense/model/ChartBlurbMapTest.java
  src/test/java/reposense/parser/AuthorBlurbMarkdownParserTest.java
  src/test/java/reposense/parser/ChartBlurbMarkdownParserTest.java
  src/test/java/reposense/parser/SummaryJsonParserTest.java
  src/test/java/reposense/report/ReportGeneratorTest.java
  src/test/java/reposense/report/SummaryJsonTest.java
  src/test/resources/BlurbMarkdownParserTest/ChartBlurbMarkdownParserTest/incomplete_key_blurb_URL.md
  src/test/resources/BlurbMarkdownParserTest/ChartBlurbMarkdownParserTest/incomplete_key_blurb_author.md
  src/test/resources/BlurbMarkdownParserTest/ChartBlurbMarkdownParserTest/malformed_delimiter_blurb.md
  src/test/resources/BlurbMarkdownParserTest/ChartBlurbMarkdownParserTest/malformed_url_blurb.md
  src/test/resources/BlurbMarkdownParserTest/ChartBlurbMarkdownParserTest/multiline_blurb.md
  src/test/resources/BlurbMarkdownParserTest/ChartBlurbMarkdownParserTest/multiple_blurbs.md
  src/test/resources/ReportGeneratorTest/summary.json
  src/test/resources/SummaryJsonParserTest/valid-summary.json
Labels: s.ToMerge, a-Backend, a-FrontEnd

#2435 [#2425] Fix incorrect widgets in portfolio mode
  frontend/cypress/configs/portfolio/repo-config.csv
  frontend/cypress/tests/portfolioView/portfolioView_filterBreakdown.cy.js
  frontend/cypress/tests/portfolioView/portfolioView_header.cy.js
  frontend/cypress/tests/portfolioView/portfolioView_optimiseTimeline.cy.js
  frontend/cypress/tests/portfolioView/portfolioView_widget.cy.js
  frontend/src/mixin/summaryMixin.ts
  frontend/src/views/c-summary-portfolio.vue
  frontend/src/views/c-summary.vue
  frontend/src/views/c-widget.vue
Labels: s.ToMerge
