Repository reposense/RepoSense, pull requests merged in 2025-01, with the labels that each got.

#2232 [#2196] Use git blame line info for aggregate blame author modified and date info
  src/main/java/reposense/authorship/FileInfoAnalyzer.java
  src/main/java/reposense/authorship/analyzer/AuthorshipAnalyzer.java
  src/main/java/reposense/git/GitBlame.java
  src/main/java/reposense/git/model/GitBlameLineInfo.java
  src/test/java/reposense/git/GitBlameTest.java
Labels: s.ToMerge

#2260 [#2259] Upgrade GitHub Actions macOS runners to 13, 14 and 15
  .github/workflows/integration.yml
Labels: s.ToReview, p.Urgent

#2261 [#2252] Add ubuntu-24.04 to CI runners
  .github/workflows/integration.yml
Labels: s.ToMerge, p.Urgent
